; tfree1.g
; called when tool 1 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Jun 23 2022 00:12:24 GMT-0700 (Pacific Daylight Time)
;M83              ; relative extruder movement
;G1 E-2 F3600     ; retract 2mm
;M106 S0          ; turn off our print cooling fan
;G91              ; relative axis movement
;G1 Z3 F500       ; up 3mm
G90              ; absolute axis movement
G1 H1 U119 F6000   ; park the U carriage at 119mm