; generated by SuperSlicer 2.3.57 on 2022-07-23 at 06:44:08 UTC


;
; thumbnail begin 32x32 1524
; iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEPElEQVR4AdWXS0/bWBTH/S1myeyRZj
; s7NJvZsJgtm2E3s2Azi1mgSkWiqiqRSg30obQoOJS0xJDmQUnqOAkhiROcxCEBf6Te361PZCL6oDyq
; Xuno2vce3/85//OwbRg/65ibm/vN+JFjZWXl7+Xl5YWZmZlfjLsegKbT6XvVajWGzM7O/mrc1YD6RC
; LxXy6XWx0MBi9d131eLpcfwYZxW2NxcfFPvAY8Fov92+v1Ekq2x7ZtjfP5d+o6Wa/XH6+trf1zK2zg
; MVRblnW/2+2+GrvuTlCt7gaFQjZIJGyuTweDrU6nM2GDHDFuYuA18VbAT/v9/vZYeR6Uy9YFSSbLiD
; LstQrLJmzwzLUSlIehG+/xeuT7ZtBu7wSt1k5wcrId2HZGg+/v5/Vcr79l77zXSw1dd6vZbG7Axvz8
; /O9XAoa6paWlvwA+ODh46HnepqY8nT4ILKsQvH+/HyiQoNN5rY0pFrMTo+Re6Z1VKhmS9MoJKvFWdL
; /yfT+lwcVLZug+Pk5PABXt2nsMYw8jw5CcK5Z81zVbrVYcQ76YoJLhUl4aGAAOl4STGTZg4PR0axIW
; 9DCSfeZc7p3WU8aejUbJdrv9DCMWFhb+uBQ8mUz+b9t2TMpLHxKlNpp0gCECFtWDgTAM2mD0FHPDZj
; MNq7B7oVwBhnY2tdfQC9VYzwEcjJfMHCb336E3rtV2fdUzhA2dG6qTUV4pXV5iOTOHUuPccwhVwKGI
; 7H9OjyRFD3bYj84kqArfcDjUbBgkWuB5KU2fWHtJeQWDgRmUSnsT+tkH1DRLekbEc/SE/hB0IuH6ue
; dtU66G73nmWN3obFZM6BlAFLnGG6gUo9gjAVk/OvoE0Gi8uZArAGGEnCW5IddK/A8fLMV+2iiVSo9U
; PNZ1o5EaF6oRWJnqeJMyFFAxWMKHTjxe02sYi570DbXWPzrazefzLw4PDzd13ZMQpmmudNvtFJ1M04
; 3XPDQdEqE+WoZcT3fGqF7YRc8UeKtWyziO84ySp13rzocRVAM9oFKpPBkREqwXuvE4mnjiMTQDFvUw
; qicMqXIdOE5GsV1Q5z8HD8EI3fNpvRiCFAqFB7DRtO2sBpZYc42XHMo94SIBw7ehBmJdGpeERul1Hc
; fKZrOPeZsCKu8YbYAM3vkYwCKK6+vrq8eO80aHBCFBESiPdkY6Ht5KQ0In9ByvG41GBnAAxUnk0m9K
; FsWIeDy+hCHFYjE+gl4yWqiOJpzMGAJDYRJLou3t7a1yXhT8i69pNmFDHhI2/H5/awzFGCL9P9orws
; 5HtztR5UWiCc3i/ZW+pKfZoFxV2WyMoFhyY6rEJNHUt8CLb6L8a0PYkEqBDRIUD89gQBKURFPlRayl
; vITBG/l/iLKBEZSr6mI754r6z5XXjYHLkE80MYRyVYZsSHkJ5WLArf2wRMtVPL52rK86JCTTcqf/i9
; EE/aE/qtcF/wgQVQlYltuTxQAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 400x300 27204
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAABPeElEQVR4Ae19zY+V55Hv+x94eXfDap
; b2Cmk2M71J7mLG8iwGaTSRr3U1iUYaLBQE0jDEQYlDMjaIxAxxSBuwbx832LidNqD2hZAxYQQ2izEb
; I2XFyuus+A8yp3q6juvUqee76jkfXT/pFTZ0nzrvW8/71FMfv6phcDgcu1hbW3vh1KlT/wcu+O/B4X
; A4HI4YDhw48L/QcJw5c+Y8XGfPnv2nV1555X8PDofD4XBIQK/j9OnTJ956662PfvWrXz2EC/4bjAj8
; GxiYweFwOBwOBBoP8DjAaPzoRz968nd/93fP/vmf//lrNCJgWDyk5XA4HI5doOG4ePHiUTQeYDT+8i
; //8k94gSEBgwL/Bj8DPw8hLfdGHA6HY5+Ceh2//e1vt27cuHETDAU1HvRCb2R9fX3TvRGHw+HYh6AV
; Vuh1fPDBB3cw5wEeR8iIgIFBb2R8vePeiMPhcOwT0EQ5Ggz0LOjFw1j4M/j3+P+XL1/eQWPkRsThcD
; hWELC5g6cgJcp5ngMvmkjnBgV/B3/WQ1oOh8OxgqAhKyzPlQwC9Szgeu+99+5BbuTNN998HAppUcOz
; s7Nz0UNaDofDsSKgiXIwCDHjIXkW+DvUW4kZHS/3dTgcjiUGeABSohxDUTFjgB4F/mwsNyL9u5f7Oh
; wOxxIDOB2bm5snL1y4cFba+KmRiCXK8WevHj365OGf//kzuOC/8XdDxgX/bWNj4133RhwOh2MJgIny
; Gzdu/ATyEan8BZbkxhLlb/zZn/3pyTB8cx048OyL1157hKGtUNWWlGD3floOh8OxgKDlubdv394A44
; HcjljICv4Nfk4iEHLj8dXa2tdwwX9TbySWT+EhLS/3dTgcjgUC72MFxoN7CCFuB4aj0BsRvQ5mPOiF
; RqQ2we6hLYfD4ZgDQolybjgkbkcoB/LuwYPPcgwHvXb+5m++lgwUlcH7aUF33xMnTvwD/Dk4HA6Hox
; +410E38JgBgXAVeCg89PSPzz+f7XVIl5Rgl3Iq8HfwHSDMduvWrXOQr3EvxOFwODog5HWEwkbceNCe
; V/h7Yq7jlVeeQMI8x3jQ67NDh55CU8YYURHCa/AzYMgo+XBwOBwOhw2kPlahJLbUmkTKizz43vemDE
; WJ15HyRqTSYSobjQjkRjzB7nA4HEaQ+ljRJHiqCopfkLcAL+OrU6ce7l57Xker8eC5EZB/7Nixp6GQ
; GjVqzhlxOBwOReSGrHglFM1DUE4GGo8pj+Ps2XtfXbx4pzZsFbvAw6ElxdLFvBNvEe9wOBytQOMxPq
; X/MlSKG2tBwktrqeGYMiAvvvh04omMLw0jsvu55DNvv/76o5AB4UYPWsS7N+JwOBwV4F4H8jpig57w
; wpM+/9lkonz8Jw9paRkP/Cws943lb9AQwv16Py2Hw+EogFSeK1VOhQh73AOB8tzt557LLs+d2vxLQ1
; pghATDISXYqechtUDBkBZNsLs34nA4HAJCA58kXgc/uUt9rGAjnglZoZeR8i4qvJGQ15FKsIfyNt5P
; y+FwODJAy3NDA5+kaiqsbsppglhTnpvrjUz9XIEM8Eao1xTyrjiDHS4PaTkcjn2PGKM81lcKyXhgRG
; KGo9Z45ISlSr2O0PX7s2f/M5XjwXvf3t7+4Nq1a6c9pOVwOPYtpPLcUF4gxTLHUJCG1xH0RmhIay8M
; plm5FeqnFfLAPMHucDj2JUJeR6j8NpYohwuS0txYaBqPqc8EvsiNG1u73JHGai0ppMVbxEsGE8mHPj
; 7X4XDsG8BJOUUKjHXKTSbKIdy0x+nQJgRODAgYjs3NmxYGRPJGuPGQEuzUGxkcDodj1YBeB8Tv19fX
; N2PhGsour0mUqzPKhaqspnLfDEP15ZEjj7dPnnwsGQ8ptAXeCCTXvZ+Ww+FYKdDyXCAFSsnvUNwfOC
; B84xQT5aw8VyuEFU2UK5IPQ98bvZGcBPvVq1d/4yEth8OxEpAS5ZQUGJrkh+EZNByxaYFRQwEbPPxb
; pXeQXcbLEuxVxiPCUaHlvjEDwsfneoLd4XAsJVKJ8lBoJjSMiU8KTBqPip/L8jpiBqCyKivn+9EEOx
; pdKV+Ez88T7A6HY+mQ0z2Xd8fF03OITKcy8CnTG2nidtQy2AtkYEgrlhuSxue6N+JwOBYaJaRAzm3A
; luc0pFXax6rptG/VTDFg6CZGsOLzwRuB7r6xZ4veCJT8AvnQB1Y5HI6FhNTHKmU8QgQ5/L2ZRHluH6
; sCT0HF66jwRrQS/FI/rRB/BAyJh7QcDsdCgYasaB8rDKOERs7ygU/UkOxOCyThJgtS4O7nwgZPZ4HU
; JsBzvZFXX328eymTD0N5JB4i9AS7w+FYGLz44ot/kfI6QtMCpZMzT5Tvbr7KG+7Mxg7McrgMZEx5Iz
; j10Ih8CAn28+fPPwq1efEEu8PhWAig17G5uXkSpwXGwlXUGwnNMI8lyrU9Aylk1VLumyUPZ64beTvw
; +V+89tqjFPGQJ9jdG3E4HN1AE+VACMydFogJXU6Ky02Ua7C9U7kO7VCZeB/KDHZekZYaWOXlvg6Hoz
; ukPlZoEHLasPMeTsFEeSTE07LBZyfKlTyeJMFRoeIrJiPGYKf5J55g935aDodDFaGBTzz5HYq5S4aF
; TwvMNg4V7PKazbrWOyjhqLR4IzkVaeiNpIiaOIOdjs/1kJbD4WiGxO3gp1qp6geIblKiXGvgU87vtJ
; bnVjHYS72JQm+kRgYYkTfffPMxXKl2KGBE1tfXf+AhLYfDUY0cRnmIXQ6EQLh4Ca/6wKeIN6KWa8jx
; eBQ4KjkJ9pbn9cXLL/9Bakwp6RC8EU+wOxyOKkheR6ojLD3F0twIGJE3/uqvnmluhtJnTXFGtEmBke
; +rfR9SP62SsFjskgZWSdVZeHmC3eFwZCPmdeRMC+Q/S0mBuMlqbYZPJC/gxIlHFsZjSoY1wZGHtAx4
; MDzBLoUgqUG5cOHCWU+wOxyOIGiiPFRVFev+Kv0snHhnNkYDtvfks5GsZyGDXMgot+KNTIwTTD7E+1
; GWhd4I5EVi3ZHpwCpPsDscjinQPlY7OzsXIfwU6q/EmeS53XNpjsCEayGQAtU9AypvzwuxMlRchoVH
; hTLQG4mFKWl+y0NaDodjFzxkhR1xc7u8SlU9WYlyTa5FKFHeOExq5pIS5doyho7kQyIjNbDKE+wOh2
; MKUqI8Z1ogz4WgN1JTntvEtcjMdWh4I8n76CCjZWAV/4zQ7/KBVZLXSUNa7o04HPsMOYnyWDxcOqWK
; TRBLyHSlXIuaaYGVHo8lwbHmGdT208qVgSEtviao3jEXBt4ITbC7N+JwrDByBj5J5ZzY5ZX/rNrAp1
; yuRWOFVYnHU+tVFP1ewiOIyigIaZVyVDDBHtK7RD6EqYfujTgcKwhp4FNoTofELsfQFg1tWAx8inIt
; lMpzsxnsrQTHhHegJSP2TFplfHbo0NNUQQUeNmCNeD8th2NFgOEEqY9VKmEaCmeFmiBq5ACmNkbKtb
; CoQgp5PJUeQdBIhMbZak1WHMLeiJZOYgl2aY14gt3hWAHAS/zqq6/+baiPVWpaIJ48aUhrtwFiDzId
; fC5wOuCyIgWy7252Hx1kTIX3gDdy4sQjbd4ITbBLYU7a3RcOKuPw1489pOVwLCHgpb1x48ZP4Prwww
; 9/DsnO2AkSjYpEFAwmypFMp70ZDuRUvUcMtCTsTTZfS/KhJYmSPjc0IEb3AwcIWqlHK/akHJp7Iw7H
; kgFDVkAKBF5HituBLzwykqVEubjBI9GtsvIoajio12HAtZi5j2FQGVgVlIGTFS09EErUbC33jdzLly
; +99BQHVuUm2M+dO3fUvRGHY4ERIgWGToqhGv9Yohw3J74pqfEg5jwtcGKsesjQNLoBoqZW+G9iBMnf
; xQZWpciHg8PhWBxIiXIp1JAa+ERDWMWJ8lquRclmp7D5JjkqGht8RkWaBaNc/PdGBntMhjSwinsgeD
; jh/bRefPHFvxgcDsd8IZXn0t5FoQtCVpJHIjLKC6qGirkWFeW5PTga3XggtTJyjXWtN1JQlg3eiHQw
; od4JDWlduXLlBOTnPKTlcMwJqYFPUpUMhhMwvJUVsjLaRJtPxyUeTy1HpdAbMSNRtsoYyhjsNTLAG4
; G1lcq3wb/D+rtz587bnmB3OOaAHEZ5yIiMT343eXjr3UOH9AclBTbGWq8jtjHGNt/m+xgyQ0WNVU+5
; IcJmnSQS7C3P68sXXvjj7ddffySRDzkxFYyI99NyODpC8jqk5LeUyAxdO2fOTJ1KkzmCho1R23ikNj
; 0N48E3cHMZIaOrfB9cB5oycgZW4dgAL/d1ODog5nWgkYglM7k3AslPCDtMbepGw5h2ZcBwJENSIN18
; NTyC4L2gccXT/DITHFEfMMlR+XnB2tpeX78HHm/o8MJzIz6wyuFQBrxM0KgOLp4ol0JWNDHOBz7hy7
; rLKOebCRgPJKFpl7IaG6gpeUBw7DWR0FLG3oTFHjImjH8DvX9+6dKdUEWg5CV7Py2HQwnodVy8ePHo
; 7du3N0KMcu5x4Aub3XpdCjFplZmyxK3ViXrKI6gtKc69p7UVITha6F0IkUFuJGZA6AEI1vj4397xkJ
; bD0QAassKkI1ZOpQwIluhSA5I98EmBhJbMdfQg0ylvvj3yLKH8k7bRFZPxGu3yE3rPYbD7wCqHowFS
; ohzbjEhkQN6ShIespGmBOTmC2lMp30QWokLKWIYGgz1bRiuJMlVe3TKwKmO98IFVUkcE76flcFQgli
; iPTQuUpsZhH6umgU8ZZZ/iBlJKWKvYGIvvo1ZGifFs4LPk3kutQSz5veJDQKHekcGO3nRo/dIEu3sj
; DkcAcLKKkQK5l0GNCEyNy2KU1866yB1cpBD+WKRpgYsso8TjKTWCPfWO3X1juT2aYF9fX/+BJ9gdDg
; Kpj1XusCdk/vLfsRj4JIYoFPIl0qalvhlKm2+sF5YGYS9hEFV00otEKem98cCAFyTYQ/20pPXu5b4O
; xx54yArLcHMMiMQyf/f4cXuiGxoMKMm1GPjUg0wX+LxuMqyT+xpGMKZ3JeNBLzqwKsRgx8tDWo59jV
; QfK5pMTCXKp6YFDt+cSrU3w6lNC3gQN25sWfAHZjZG7c1Q2Bin5FnIIGW/SysDnhEYD9A75kaUP5+O
; zw11UPAEu2NfA4wH8DpSfaw4uzyUaBTLc43IdFPhjB4jZ8FwAGHPgAcxJQPuw2jTfYIbfC+Co7XemQ
; eirRtksO/xQR6G3hFPsDv2FajXAdMCocVDKlSFHgaU8Uo/GyzPxTh1QWK6aBOhPZQqyz6z5K11aOfR
; UUYqx6Mmw1DvJrkv4V6w3DeWE6TeyIULF856gt2xkqCJcljsdFpgbKIb72NFfza3PLd5Y6yoxjEZ+K
; S5+YbCYr0Ijp1ktOg9dGAI/kxjXkf6vrGBVdyIeILdsXKARSwNfEq552g86N/ji8JbkWTlCCqJbjmb
; yMz3aGUyr6WJbtobVc3PzFtGVll2pdFdNL3zgVX8gMVzJh7Sciw9aMiKl+dKfA58QUK5Do3y3GpGuQ
; EjWdyEjPkTRb/XsvmWyKjwRor1niujwRjU6D3obQoXTbCHCk08we5YCeQOfOIlihDWgouftLL7WCls
; PkWnT4WNqPokXrD5tpz2i4xgZfiu5PvVVqR107txG5vtkycfQ/4w1hMO36v19fXNa9eunXZvxLEUSJ
; XnphKBGNqiJ6uaPlZZL/raWpdpgTEvpjmMk7sxLoGMLBKlhoyU3jW6MMf0rlCW/dmhQ09T7xa+U3Ag
; g3cRxiG4N+JYWEheR2paoJQonwx8euuthw++/e0uRDdtwzGzYbBTqfZ9SBsj3pNamWlo81XmqHTpxt
; tB75JR0rwP3k8rRjz0cl/HwiKUKI+R/2KJ8qmBT3gqVTi1xTasKVa5gYwZJrPRMKYuJEq6+faQocha
; n9F7jymRxnqn43NDDUd9YJVjIYFex/nz53+c6mNFvZHiRLkRmY6HGqw2xMl9UPKh1cbYg7DXi+BoIY
; Pnp6zvg3s5BnoHT12aesjfL55g93Jfx9xAQ1bI64iFqtDDgDyHFNZKJco1T7zB0IUm1yJwH1YktBkZ
; a2tfa29U3CMwMYLM2+yhdytvakYnBuEyKgMHVuUm2D2k5egOKVGOp5/YwsVQ1rFjx57y2eXZ5bkKG2
; NOwlS12V/As8n5HlUbVcbfa8qo5dhUydDUu4GMqc8K6V2xc4H0vGIDq7gn4uW+jq4IledKDd9ChCf6
; d7/4zneqNr2ajTHodSjKKP79xlNpVo6gdWPMyT9pbfAZOqnijCyY3vl30ubBhBLsaDx4f7nLly/vuD
; fiMENO99xfRaYFFvexKtjYLDaR1o2xdBOqOZUWy6g1uj1klJzECzyehdZ7ZSizRIaUYOfvokQ+fPXV
; V/92cDg0wPtY5U4LhFxHiPDUNGZ2mN18gy+6Ur4h9/sVG8HQZpdzTzX3Ump0a2Vkbr5WMqoNh/A5pv
; dRoPfatbXb3ffkyccwuTOWo8R39+rVq7/Z3Nw86Ql2RzOk8txUopxOT+MGR0yUK1Q/SS+w1iYytWn1
; ILpFDJ6KjCFudIs9gprngaE713s3vYf6aUlRBHh3PaTlqEYoZJWaFkhneHBi4LuHDs0S3RQ2w6mXcO
; /EmH2ar9m0+Oe1eASxTcmQhBZ6/iY6YZuvqd4Nqtu4jKn70F5bkt4V1xbvpxUKQePhzxPsjmKk+liF
; pgXiIqR/D383IQUO34QE1DcR+gICYQuH/hjIoJug1X1MNi24B+CNAOHNQg7RRU0yN/t5GRMcV1Lve/
; djoRNMsENFpMRax7ylM9gd2UDDQacFxgbZ0H8PeSYhUqAZ1wJPb7DpWnAU2KbYhYQGz0up7DMoQ9mD
; Ct6HlfEgpECLZzQlD2V0WFsm3tTe9dnx4485+TAnwe7eiGMGnBSY6vaJF7i6SAykf/+Pzz8fT5Rr19
; wHYt5qMvh9kE3K5DTKOtvyuL4aR0XSieZ9GOo9luuw2OC5ni30zsNiJqFYEhbDct8Ub4SSD53B7phA
; 6mMFxiNWbUUXFXV1Q91zo6Sqxpcwtolw+Wov+JoN0S1LhlKMP/bctTaqWI6gh941N/iUTnrIsNR7Ks
; FOe2l5Py3HLmh5Lu1jxeOhoW6fOdMCs17ilpr73NCOBpku4+TfakRynlfrqTRbhpGBmtFJqR5KNtNG
; vceM4NTPtRjdzES5td5TCXYarsaQlreI36dIJcp5BRUlI9X0sdJY4OKLVHgiq9kYi3+n4lRaK6PkGe
; RuhlMySjffzM1w6nuVTO9bYL13W1uFz2Ci90wZmGDH9z02CM4T7PsMJQOfuDcCoa0333zzcVaivPb0
; mlNz35oLWACim9bzyj2VNsvI3aiMZLSevqd0kvNzLUTNHnrP7FxQKwMGVkEuVHrfedQBcqA7OzsXPc
; G+4qBeB9Z550wLpONmKZkQEuWaLwV/QWZq7itPnzUvl9p9pGRo5BsORMaotmyGXMZagvltIMNE70aG
; tkjvWjJiej/VVmwR66clkYbdG1lRwIlA8jok3kYqUY7XzuHD05uSwoINvWgWm8jU9+5IdDOTMQzibB
; N1GWtCJZIFmc5Y79KzMdO7tQwWytSWQftphaIT9KLlvoNjuQEngXHo6SehgU+haYGxRPnUtECDBTv1
; ckAtPE4LtJCBLza8hC+++NSyvh83W0vOxWTT3XtmJvdCvBozvYO+jUmBk/ULerdeW2vGRE1jvaM3Ih
; 0mpQQ77DVe7rvkwPJciE9CPDPWTI0mx/G/U7mOycthQKabOX32ILr1kIFGyvo+LEloaEBc7/kyjEiU
; UzLwXoz0Dp/3+48+uhkyHp5gXxHwRDlOC0w1QwTFhwiEqUS55mk0mDBtLcWVLp4jsJAhPa9eRLfWxH
; OODC29hza/iqq2LL1Tj8BK73NaWzkJ9loZWO6bMzzOGexLBqk8N2dWMg1Z0WmBReW5GjX3GTFvq80w
; 99+KZQReYrXNN5Yoryj7LH5evfSutPl203uvtRUiarZWK0bWFk2w53T3lbwR90oWCLHy3FCyK1brzZ
; sgphZs6wuSu4lovYRZv6+xMS6CjKHtVJotQ0HvFmtr5jnk6KTh5L5Qa6shpJUjQ0qw87yq5I2cOHHi
; H4CEODjmj9TAp5ABAc8EwlvFfaxyrtwXpGWRV7yEMY8gtumYk+lqN99SGYWn0iq9Zzzf0gODit4rnm
; /V2rL8XrVrqzCUWfK9pAR7iHwIe87t27c3Pv30059BcY+HtOYIqY+V5FJKxgPqtmloKxiyqliwuQux
; aROpWOxNp9cDeSQ0FRmWp/BMg426qT4hp7gWS6L3bmsr1+j20Hul9wXkQ9hTYiEt2Hfg0ArXrVu3zn
; mCfU6gISsszw0ltfioWTowZmrg0/HjT0y4CiGuhWaiL7b5NhrBLBmKz6sb0S1wKjXLAzSGVHLX1pR8
; LaKm9dpaEb1L/bSkYVVQrANGxBPsc0CojxVNfkuX1N9qlxQ4jmNak5HwBdktY1VK6ua8aCb30UEG93
; haPYKgDK537ZJWyrWw1LuREVyItWVUgTZVKq2s99TAKlrc4+W+nZDTx0pqdkiTWtwb4dMCJ9PvrMpM
; O0yNMye6oQwjQzsjowfRDYl72psV17vBupqSY7AZruTa6qD3L1577RGlEEiXl/t2AhqPsfv3y1Aprm
; QwQkmtX3znO7vDZGZeQKX49Mzn0s/EDdFyI9EKX8RkWG9W+JL3IjhqlH3OW+89ZOzpxErGxEj1IjgW
; JthL9P7luXP3tk+efBwyIE4+NAbvYwUWHWKIsf5VeEEnTanXlZgoZ8ZCi4wUM0irEmZoLfvMlqG8Mc
; 4YWcUcRUrvXUiUvraKZKjrnawtLPeNHX6xcSvsbz6wSgHSwCfqDqbasGPIiv5sSet1vgmUvvRZi1Lp
; BYl6HIqbb+xUuHQExxy915Qw53iwmVVt2XqPydBIoseImlprK6aTXmurUu+xAwNeqe6+uG/xkJb306
; qAlCiXqql4viM08ImTAlOLaeblKTid5CwmzRckd1Nt2Xy7ych5Di1G90Bm1VAPvfciUXaSsTJrq/Td
; LdS7xGDnoXYPaVUiN1EutSaRuuqWeh1ZiyS3xt+aVDUMecxi/oIYMbGnZBRuWrX33oNMV6V36+dbGm
; pZFb13XFtJfTaEvjCkhZWjoZCWj88tABqP8QN7JydRTuuqMTcSzXUMbaeY2IKp8TpaXpCm+xjyNt/s
; U1vLd8z1CBqfQ7PeY3msZdF7r7WVK6OH1926tgIhbA29Q0jr92fP/ifft0Khre3t7Q/cGxHAvQ4k+e
; UkykP9rUSvw6DKYlLSqLGJZL4grS94TxlJopuWjMCmNdF7q4xhkAdWBTYY1/sC6F3xPqa4Qg1RBumS
; +mnFSNA+sIog1McqNS2Qxgx5SOvB9773ZOaUqLGY+MJCzgj8qWQ4Yi+IphEMyWj1CELXShHdgDdw48
; aWqd7J5mu2fnuvraHNI4jppMvaQr0rHhTxov20YqF6H1i1h5w+VrFpgbySAX52KlEOi3dveJH6yzcw
; 0qHVRkJlWZPp1tb6DP0BGcplmVMX6v2UzfS7rnq3Juz11ruhjF2949qy1ruBAcEL9jDc86Q8Lw/f78
; uQFnod0I3ywoULZ2O5DmowsC1ASaLc7DTC2yAourQzLwZuJIYb79SzMngBJzKWlUTZIZQxcx89WeXW
; a2tZSZRC/sta718eOfKY9+rjkZh9y2Cn5bnYlRIIf6lcBzwseKjceGQlyisqUIKLNJTraKjIiMrjMp
; RfEMnAqhvdvZdwWUNY+0bvRkbQVO9CyLWb3o3zXxDSSuWC9025r1Sey9uphx4UDWNRnkdpory56iMj
; Ua51OumR6Ix+jqbRjclQ2BgtZeTqM6vsM3Ul8k899O5rK6D3IaIvjQq8gBHCBHuMNI2lwCvrjYS658
; bifBK5Bq9//da3noX6WDUtuohyixZJze+Ufr+WFySyYNVkWOqkg4zcA0Psd0y4CgfqGeypA5ba2soM
; u3Up4+2tdwNuksRgl/ZG6o3gYX2pvZFQojxVpkYbIaZyHSULtvQFqVlM/AUpOZXWbKRVL8gCyig9lW
; Zvhr31XnEqrdKJwUY1D70v0tpqOQD00Dsm2GO5YJ5gR/LhsGyQ+lilEuV44zBsRZrspcEoz/19q6Z6
; 4qLM9QhaX5CWhOyikdAs9K6Yz8g5lVYZwdLnUHPAkvSu8V3mvbZiemg4KFbpvVLGly+88EfYG2N7Kf
; LjIGf88ccfX1m6kJYUsooNeqK5Dimkpc4olxavwWJ6wl/iU6dMO/JaLNjcz2rdDLO+b+tmKHzW0uu9
; B5luzmur+YAVkWGm98Bnaj0vqZ9WiD+yNAn2WB+r2LTA1MAn+oJoLlj+gljMhJhZvLT816A2XnxBtJ
; /XvIhuFnpfW5ueBaJd/sv1DjpfUr13W1vWekeuEJ0FYrWn4OefOPFIe23xBLuUDpC6+y6kNxJKlEuW
; MdaFkibKZxavERlp8oLj1DgDGVOLF6egGS1ca1LV5LntybB8XquqdxO9UL1b3ochUXOiG0MOTE+978
; oy1Dsm2HH2ETccC1/uS72ODz/88OepXAefFphNCiQkHvVadepudiS6TZ16LWQYndq7ytgzgibP6NQs
; Qcz1vjgyWirOsvROmf5WBh0jG8pcIX5Pnx0//jhUzSol2BeinxZPlOdOC4SbQw5ITaJcZfEmEqbaL4
; iUI+CbWPMilnIELSWZsXvpLWMYVIhuqZi3id4lGZohMylHYGF0l3htJfVuQaI01vtkT9n7/9TAKp5r
; nms/Lak8l9LvU8QX7o2IifKYC9vwgqQWk8niTdxH6+kktfFZLNjS75B1HbAj0xXpvQfRrYferdfvoK
; N36YA1F70rHB7mrXcs940l2KkR6RrSSiXKQ9MC+WhZevFpgSWLpfQFqTkFVC/eAwWkqobTSfb3ayWh
; lcio2LQsZdS8tLVGF3WZvbZq9V6ytnroveVAZ6H3ms26df1mPoPqUGbmngLeSIhoSPfkrgn2kkQ5vT
; DBU9XHSmkBZp9ClF6Qqpe2cMGXLNjqF6TACPIXxMQIdtZ76feq1nvBd6yWUaD3lEcQ+z3ztbWietfm
; wWBI6/z584+kPoJSgn19ff0H6t5IzpjZELscvjjkO3hcTn3gU6oevsV40M/K+I4tJ76Z72tUf5/9Ej
; bIyPF41GSk9G60tvjaaF1bqVPpMui929qKPaOa032N3iuN4MzvJ/amluf1xcsv/0EiZksJdvg5VW9E
; 8jpSHSKpVeNtiaE8d/u559QeTvRBF57sqmTwv9dKXIa+e+uCHfJeEDWd9JAxTBt2zQNDtt41ZQin0u
; YDFteJtE6XbW2tqt75PSnIkAZWxaJGzQn22MCnWD4DvxDtnstJgSabIV+8QNwxWEyhF0RzMfEXZIqM
; ZCGDfHez++AylKteJjqh5LBl1Ts/lVrxYAw2qiy9W8joofce5FljvfMEu2Q8aLnvOPz14+KQFvwwNO
; GCX4z1seLs8hApUJwWaEh4mlhzmB5mJGMiC2q8gShk8PJN3Q+SkSw2XqoTw/uYvCAWOsHPps/J6j5A
; Jz2ImqB3WMOGep9svtZ6tyaDgt7hstZ7DxmwjkHnKEtZ75hg59EhvndXJdgxZLWzs3MRBeQ0QaRzOn
; IT5dpWXHJhrU5W9D5i8VhtGRYnLOoRWG6KlLi1MnrvtLbM9R4INzVfGIo18Drnpfdua8vIo0IZ2ydP
; PpYqZkMJ9qxyXzotMKfrIwiFKiu4UlVWogtrRBSaIVUpvyDSIlpaMpIkw2DBzuhdi2sReh7aej8wJ6
; LmsDp615IRNarKBzrR+FnoXQjnV5f7ZuokNbCqOMGOFilnWiAPWaEXUpMor1WGdArJfXgaCjCTEdsk
; lE4nX6WImlqGPfa8GrkWK6n30M8Uln1GP2Oeem/lWuTq3cjQlvy7mozGw0NsT0kx2PnUw6g3IiW/Q9
; MCJav17sGDz6QFm3XTNVyL0o20dfEuioyh/nRSJKPyBUkawQYZ1XpfNKJbrYzKkFap3s3Xb4vejdbW
; 1O++klng0xDKXCS9ozfCE+x0n+cDq2b6aYX4HCQrHySlqAx8Kqm9bjiBl7wgJZthy/1nL1guw5CMRJ
; +31X0X6b3R8yrR40TvpTJK7r/kgBXSuxU3aUH0XnVgKJTRfB+1a8tS71LINXHx7r6h0Bb1RrDgajek
; FUuU47RAbkAsBj6Ffr95MQkPuOZ7aC5eFRkJg1q7YKc+w2DBzkPvOc9bSyc9ZCT13mP9tq6tgIxl03
; vPtWWp99uvv/4olLrgRuTq1au/QW9kSDHLea8r7TGzMw+KLKzSU1eNjBklKd1L9AVRlGFJRop9lone
; Q/elKUPS+ym9uQ1WnQRWVu+oX4UoQ4neNYxgSob6nhIIYWvpJJZgl1IckGAfUolyNCTI67BasFMPCm
; rIcQCT5mLiC2jvc63ug74gqgtWWqS0Nl77Xg50IlHi919yvXdbW/ic4F05ceKRydpCvStvhlMy4H13
; vefLoHofPzvNz+cJdpoD4flx+HOoSZTjmE71BUsfEBLELF4+unitiG49ZQzDN2QkTW+Ny0C9W3x/1P
; ve1DiL7z+jk2VfW/Dc8JlpemuS3q1JwLgZGup9V5YxCbjbnmI85RQcBlqZKxVWgXEZwNLEEijB8tzC
; RFX2g2enEFNGLiFVWXog+PlWC3dKJ61lnzkyFPUuxry115Z0H6u2tnroXZtrMS+9W8qgEQdDz3Oytr
; RD/ORevnzppafgjYQ6scO164GgAaEJlJlEeeDUpvGgxMWkLCP5eRYviCRDe/MN3IdaOCCQI1gVvXdb
; W53Wr5beQyFXNa7FftF7jz1FW+/sM2IDqyYhrNi0wOTDbq2LzrGiGptvRujCyUiFeq95QUoWvYLeQ5
; uhpoyFWlvGeq9evwcKyrIVNt/sfatV7wmvr1nGAuhdGli1a0CkJPp74x++n/nFp75AaV107mIqeJAa
; v9dDRtPme6qMqFlzOinJEZS8IPtd700yct+vWr1nGMGpn+2hd6vDT+XPLrKM2hB2ztq6vFehxTuVBM
; t43z9+/PEDIzJd7WKaelAlm2GN8mpekJoFUmp0axdh5unEcqE3n5JKjG7JZthb7x3X1tTztpCRo3cF
; EnDpJmq6toayA9Yy6300vv5+HJHiZbyQYIdriNX8frKxcQe8kdIbiNZetxgO4UFZbIZFn1G7YAu/Z9
; WCFb6nJRmpm94TL2EPvRd5BLXfs9YIRp699H2XQu8Zm6+K3hdgT1FbW7HDWsbaevu558Qmi5RgPvDB
; URKB8Bdj9+V+44PS3kRSytBQ9NTDDr0gyyRjkE8nGgt2ZfUunOCWcm1JFY4GawvvI8dwqeq99YCVI2
; MZ11aF3tHrCLHRqY0YcAYIuCN84AhNsP/wO9/5+matN0IJYooLdkrG3kuIC1drwfJFOnlBFBdsaAFp
; v+BTMigZSbFSZEqGMRl0Ru8G94H3sqt3BY9gYfQO0y4t9E75SL303mttWe4p1msrU+9gPI4cPJjViX
; 1iQMB4wDwQuMA1idHZaYK96Iv3nBpnLcOITEcXVZeph3ukPe0X3fXepndTGah3gwPdRO+9pgVmxPhV
; 9L5Ke0rAsP9ufH1/7HVgFIpPng01WRxgBu7Gxsa7//Ef/3EdLjAgwAsJNdVCb2Q7dzFRF7a28ij3AZ
; ETg8lpAU87PWQM6XisioxUrLTms6UQmdUpkerdki3dU++dZKjpvVOIbOo+6Mm9x9paoT2Fv59SyAoM
; BnRiTw2f2p1IePHixaN37tx5G4wHeiCpplo//e53n0oJ9pyYt+aD6hGvDLmwJvFK/nnKL4j4nQ/Ul/
; tm6135BYnFwpdubZ2yIWry5yLq5FRbfmoh9L6sa6tXDoR9HtXZzpkzD0PDA8GRQG5gyA7sGhDo7375
; 8uXj4I1sb29/EJpOyOegw580wZ5jPDQfVPIzFE6lWTIaF283GamSvlfyy/9CC3IR9O5rq+xZqOjdun
; opI0fQTe+9ZBjq/eb43zbGxkPKd3Ojwfd9WtI7wHQpNCLw5+bm5slxXuSXkBuhCfbQvHT4UPBGfnvk
; yOPik0zlgwp5BMGfb+Ac5N5L7eIt+b0eMkrISCWGQ03vq7C2huFPC7m2SoxBrd4rjG5XvRvKKN5TjE
; iUW+PI0TnS4ypneCDs85gvp1yQ3amEMFkKjAeGs+A6d+7cUfiBnZ2dTyC5Dv8tzdBFawT/fu/SpTv3
; V2ATrT7JFLwgRQt2qFy8hQt25vdSnJHW8EcvEuV+XVu1G5zrfWFklHg8KRmQKD9NGOUSMTCVuoAUB9
; gE+G9wNCajbcGIUG8ELjAkN2/evMpLfCVXZu8D7106efLxdsbNhhZvcnHXKIErw9LVHobFISNpyBBO
; pa35ElEnse+gkeRN6d3XVlzvCvmSku850XuDjJXZUxRkYKJcmu/BPQspdUF/dmtr69MLFy6cBfswcK
; ytrb3AjQhYGmQeoiHhnJGZL1VQ7pt6QTReitTnqSzY1HfGl1DrXg50JiPR8k/t+xBeEAu9z3VttRjB
; 1HfW2Az559FSbEXj0V3v89xTFmBtfV8gBUqEcckroYZj77/fwXQH/DlIoN4IhrWuXbt2GmbhorVKGR
; D4gpBg3258UNpKmFq8PcpM914QMxnDNy+IqQyoVb9xY8uSEDqld83NcBX13mttgb5B75gTs5CxRkpZ
; e6ytfbKngNcBISteZYVeSMyIIDeQksxhhC0aD7yGGNAbweQ6GBKwQOCNgBsTEk5jaMAZqemnNSFVKZ
; 3agsroQXR7pcNkOiPC01Q4o8fIWXhW1pPpOhA1d9dWLxKatd6ZB2LCVXilA4myx9qC52a9tjL0Dn2s
; /vr55yfhJx6O4lVX3HBg3htzHdxwgIMx5IAm2DGsdf369QuQSKEhrRR3ZOvQoadFDHbj00JvGSVJ0G
; IZnFSlGSoRQhe1ZZ+udwO9owxrvWck2FV0ohjqm6fe57W2RsMsKRCNBPA6QqRA+Hs0HjRdAV4HOA7U
; eIBjMZSChrTAGxkbkR+ur69vghBKPgyRUo4dO/Y02U9rz4WdWUA9iEI9ZCi/IEEZrYu3tBqn8Z6mjK
; DwPTSeVTBHsEprq1FG6MBgqneL9Zu7tjSN4LzW1vDNnjIa5CaI6HVgixIppAV/T5Pp8N/AC6QUj2rj
; gaAhLTAg8MEY0qIJF95wi5NSpAR7zqJReUEyZLQsrOCCVZQR3AylxVvz/XMTpgqn0iydGG1UpT+TpX
; dDGcEDlqCTqu+/SHpX2HxXbm0FvieU5350+HCQMU7/nhMFpUpazHWoGQ4KTLCjAAxpQT8tGtJCUork
; kcDf/evBg8+2ax7wopORFklG4QtSe7qs+r0cI9hw39U62W9rq8EY1Og954BVfd/8nhZtbRnIGA3T3A
; 70MKTDu9TrilfWQnkuFk6NHYOfqBoPCl6lBRcIB0/k/v3712KkFLyAM/LZuXPlibOCF6R0wfLftdgM
; axeh1UIvOn2mnoFlO5MavZfKGAqMbo5HsB/0XtK5oIfee62tGr0rHrDe2AtXSdMCwTiEGuLiz4PBgJ
; wHFESZeh0hSOTDK1eunEDyoURKkRjsvy5IsBe/IDWLSVCkuYzI4m1ZsCkZKpsIe0FiCXaN59VD76u+
; tmq9zdh9fBVrqFh5wFpFvbfKGA3hRDnlb8Q6h6ABgevDDz/8uWquoxTUiKA3AiEtzhfBeJxU+ts0sI
; q/IEoLNipDaTGlPs9MxgFdZvGMDHYq1b4PMSTQ4BHMVe8diW7aB4ag3q24SYLRVTlgpfS+IHvKaHxB
; eW4sUc73VmnaLOzLly9f3jl9+vQJajhgLwfHYOgNmmBHQ7K+vv4DakTgv2nFlpRgHzWOz1VfsCEZmg
; tWekG0Fyy9j1f2psZZT4mkDHajgTlmG1VI70u8tnb1sbl508J4dNX7gU4kyt56j8jAPla5ifJQnyuJ
; UT4Xr0MCD2mhEQFLBzcAA6uQpBLr+pgzsCr4ghixZadk9CC6GcngISarF2P3gheckg+tNsYehD3USQ
; 8Z2s+Ih5h6kOmQeGql9wOdiJoLsKeMhm9CVnRaYCxRjh4HJQZCriPEKJ+78aDg/bTgAjbjgwcPNsGI
; YDfHWIIdeCMfvPDCH3O8EX5qM1uwZMO1OpXQz9WUEQxdHKirPCq5j5ZKnyIZQkhARcYSr62Q3nusX6
; swaTe9k+9rIYOHXCWdvBHgdYAhkHLLUo4ZDcj777+/2IaDQuqndf/+/fOQYKeElViCHf78RSKkFXoR
; 1F9C6bMUN9+ojMbFK+UkpJ/RekFCno0UI9d+Xj303m1tNcpIPm/NzTcSck0VVrjeZ5/jaJBJgehZwA
; E7NS0QQ1aj0eh3kCiHoYFLYTwoOPmQ9tMKkQ959YDYTysnR6C1+SYWjdVmWPoz4u8UnABbX5Cs3y8o
; +wzKSD3vVr0v+dpaRL3nHGKav2PrgS6nCEND74m1BQOffnryZPRgTf+Ocz/oBd1CaPfcuSbKaxHqp0
; V7rmCCPUZ8wQR76YKv3nyNZWQt2MoXpHQTaX1Bip9Xxal0VfQ+MYIGMhZa75WhzJq1Zb5+DdbWaJgd
; +EQP1qG9kU4LpKTAuXA7LMH7acEFFhJyIkA+xJsPxfXg74F8+KDmlLGIZKTKU1/0BVHKN+R+vyyPIP
; a7OSGtHI8gphMjA9VV7zlcIYV8QxGjvGVt5er9VAei5gKsrdHwzcAnXm4LB2uJ04EX/jzkOTC/jIzy
; lTEeCN4iHm4QkjuhkFaQAKM4sIov7NaYcGqxaFQ/STK0NpHcF6RlE+EyQt9ZRcYQz/GUegRVz6PFCM
; 5D77H1uyx6zzG6Gmsrtack+lh9P9IAkfPoQnsiIQb+ciUNB4VU7ov9tKgbFovtYYK9enyu0UYVW7yW
; MrJPdRoviNJmOPP8jUlowc1XWycS0c1K7wbVbVwG15H22uKhTJO1Zaz3GhmjId49F/MbfFAfNzALze
; 2wBC33RQb7pUuXforEF+zVwuf1agysmnkJNV8+9oJYbIZTixQIWzj0x+o+1uxJVZMEO/AHgPBmIYfo
; wvW+YHrfux9NAzWj9xdffGpSij2UrS1IlMcqUOnfSwOf2Gjxd1be6wiBJ9iRfAjjc4H4guTDWBwwp9
; w3+HIAGcnqxTCWMXVqh03X6sVAeT1IlPi8lMo+gzIMjcdc9G50H7vykLDXYW2ZeFNMJ+brN7K2RsM3
; XgcyxvFAHCrLxT2Ocjow17HvvI4QpH5aYyNyGcmHqe6+mGDP7ac1daJSKM3rKiNC0LJ40SdxXOm+tC
; 6JTNdQ9pmtkx4kSiW9x3IdZnqnMgz0znMEJqFYHmVI5His9D4a5JAVhqFiexsOfIKDNOyH29vbb/M+
; VnAtVXmuNng/LSC+fPbZZ7+m5b5Sl0k6JCXVT4sv2OAC0FywijJim8iUfKUXJPh9tTfGkAylGH/suW
; ttVJZrK0fvmht8Sic9ZJjqXXv9Bp4J/NvdsQwpUU7Lc6XQlZQohwtIgcCp2/dehwSaYAcvZK/Ud7ef
; FhqS1OCUUD+trBes8QXJllGxeGdOZwYypn4/k4RmTqZrPJVmyzAyUE1rq3QzbdR7zAhO/VyL0c3MO6
; 6C3kfja+PMmWAF1UJNC1wlSP20Pv744yvYzReJM7HBKf/0rW892y33zVywrS9I6WLM/fksr0PxBSn+
; nQqPp0pG4ak0dzOcuY9SvRutrUXXe7e1VfgMJnovkVGq94wD1rsHDz7jFVR46I31sXrzzTcf86gLbY
; CIf7rhSID30wJv5Nq1a6eBfAjEQ0wkxZQB//b/L126YzGwqnrB8oWY4lpUbiI1L0j1iayHjCH/VNos
; I1fvRjJaT985a4v/3ELr/ZW8zgWLoPfR8E2ug3sRYBjAQIRIgbwJIk4L3LdVVhqQyIeffPLJpVzyIV
; jxkgR7yQvS6gLTF0SqudesSonmAbTuIyVDI99wIN5PS6XCqofeI1wLVb0bGdpivWvICBnVzJBrlk4a
; DNTbzz03M/CJzucINZGlP4Oex1tvvfURhO9prmPp+lgtCqRyXyAfIl+E5kZCUw/h31oHVvEFq5GE4z
; IsNpHYC6K1iUzJkDZGg/ugz0hdxjCb41Ezgp31Lj0bK530kGGud+lAF5EBjPK/z0yUc06blOvY19wO
; K3AGO3gje7yRTSQfcqJNboK9aPEaLNjJ50MtPE4LtJBBXhBTUhV56VQ8gpgMJKGNn5kZQcxa76BvY1
; LgDJnOQsbwjQeofcDqrfcpw54IWb126NDXuYlyHtLiU1qd22EMGtICA4IDq0ARkBtBsg0Ykxgxp6af
; 1u5iMiAjzZw+DTfdibweMqw3K7wPSxIaGvZOerfadLvqvQdBF+/FSO9T9xHQCS3P5a3VYw0QscsGXj
; Czw3MdHRHqp3Xv3r3LYETQqqcS7Bsvv/yH7dzFtGZDqgrGdiuqm5JXiFRlTULrRXRT3oi76p3pSEPG
; 1GdSj6CH3juurZwEu6beR0O4jxUcXGPGgybKsdPG+P/foB6HG49O4P207t69e2Zra+ssHSQfS7DDn6
; l+WsFNQ6PmPiPmbbUZ5v5bsYw5EjVryj4XUu89iJrDbI5nqddWpLBCbW2N/15KlPM9hc4uD5EC98Ls
; b0AofpwwP0wT5YOjH0L9tGhTRppgl3rOSP20Ygu29QXJNR5aL2HW7zd6PEUyWjbfjO/Yciqd6F3pu8
; T0brG2qnSyoOTZmvuoPTzk5Dr+/fDhJxJjPLSn4M9KCXSY2eG5jgWC1E8LWsQjKQcT7CH3EhPsUO5b
; /OLmviAti7ziJcw1glO/U+rxHCjnEVRvvqUyCk+lVXrPNTa1nlGt3hdxbVU+32q9l5A2E8ZDmhYoJc
; qlkBY9yMKFfayoAfHy3AUA76cFRgR6x4ACgXiY05QR2O23jhx5rE0+bNpEKl7CltNrDxm5Hk+zjByD
; faCtLDvJtXC9z+hkEfSeMoJ04BOfFohGIZRjpV4HHGJh/8FEuTPKFxhSue+VK1dOhPppSQqHn2kaWC
; XVw2smeGMnxopTW7GM1hecfk4volvg+avKWGNcIe0qocjmW+MRzG1tDfH8yyLofTTIiXI0IjnTAunc
; DpwW6CGrJUFOP60QmSc3wZ5cvFDGqpTUzXnRtF68ecto9QjESyKhaZe0Uq6Fpd6NjOC89a5mBLlOmC
; 5Sen8jQgqkuVROVD527NhTb4C4Qoj106LEQ+qZ8BNF08CqDlPjzIluKGMtTapSkQGbr5WMYS/BjsQ9
; A47KlN4NeR2TjVDbCK7i2srU+2h8HTl48JnUaiSWKKf9q9gE1Xfc61gBcCOC5EMg8FDyYajRGU2wZ7
; 0Q9MSDG6I149tQxuSerElo1hviQAhiGmWf/HN7672HjD2dmK6teeid3dNofGF5Lp8xlEqUU1IgGBDo
; Y8UHPnkfqyWHlGB/++23T4MB4eTDEAkIDMzWoUNP7+duIqsaXlI+uYsylDfGmfCIYo4iqvdeJEpfW0
; UyUFd3x/8W6mOFUYncRDkQAz3XscLgCXYg8Gxtbf0blPty8qHULRMWTHBgVW61j8YLEssRaJLQIqdC
; NRlrnUhoaxnVcbUlzDnVPlr3EVo/WnrPINOZ670Tefb3Y53BwKdQQQ2+76lpgWhooOITDqZuPFYcvJ
; 8WXHBykBjsIRcW+2n9V+T0GVzYDS9I7mbUsml1k5HzHFqMbm7VUIU38lWp3juSKPf72sopwthhvA76
; vofGZoe6fQMpkBbsuOHYB+Djc+G6cuXKGUo+xD9TA6seVMTSa16Q4jhxxeZb/L16EN2Gco+nVkaONz
; Lzc9bPt0bvNfe+aHo3kDEaZkmB6EVgJ+9YCDs2LdC9jn0IXu6L5EPMi9By31Bfm082Nu7ceumlp9kv
; RuEL0hoCyW7JYn16rdkMK56Dxuk1mMcq9DbnpvdFW1stRM0C7yv2c9DH6l/G4eeQ8QiFsHm1FewLUM
; nJSYGeKN+n4P20sNwXvRBa6x0aWAWX2sCqipdnEWQkiW5aMgIb48QItsoYhpl+WmrGY1X13kvGgfJG
; naNhmhQYe4dD7UoIIfCeex0OEbyfFvy5vb39AfVEKF9Eui4cPfpkW+EFafUIsl7CRo8guGmtEtENeA
; M3bmztcgiUDMeMTojRs7gPcW2dMiBqsg1+EdbWaIgzykMXPzzi350/f/7HXmXlCIKGtJA3gv20sClj
; zqmlZmDV5KWzJtOtrfUZ+gMylMsyZzatPRkW97J7D2A4NjdvmhkQqncL4zEvvRvKoHpP9bEKEQDx7y
; RvBEmBe7M6HtJchzPKHUlI/bSgRfzVq1d/A03RJC+EL1KIoRb30+rB/B36kA93P78XidKCa/GKMHu7
; ttw35z56kOlwbVlPiZwziXI0zIasaKsR6V0NMcoxZOVeh6MYUoL95s2bG7wSI0Q+hIV6bX39Xk4/rR
; mjoVhzzzcqvqmY9B7qEV4ykBHNdUQS7Fr3YaZ39l2tjKBp6FIIuXIZkCgPVUymxlzDe43Gw3MdDhXw
; BPv169d/CAl2Tj6MkZFS/bTmnUytKfusltG4aVnKyPUyWgZWzXzOCiTRkzpR8HhSMn4/lgF9rKQ2RD
; SMhXyOUJUVeh2U2+HGw9EMHtICbwRCWnBqoXkRTM5JbjLvp5UdTmjZGAWPQF3GkL8Z9ZJRsjFGvY7M
; 3zHhQzRsvtmhvda1lRl2sywRH42vS2+99TBUbh8bac2T6dDH6ty5c0cx4uDluQ41wAkETyRIPoQW8V
; gbvrW19WmKjASLFsp9/6vi9Fe1MS6gjNKNMXszHMo3xhrjMbOBlhqeUp1YT/5b5LUVWSeYKOf5SNoI
; MfQews/g4Y+SAqnXAe+3ex0OVQQGVp3Z3t5+m0495G4y9URgwQL5UGtgldYLPiUjd/NdZBlDxOOp2P
; yj3zER+qoygqXPocAjiOpE47sY6300TCfKqSeBhiG3CSL8rCfKHV3B+2mBIcF+WrR+PMZgB85IS7lv
; DalKY9Nq3Qyzvm/rZih81pRM5WR4zCCp6aSBTKe2trSImjG9J0KCoYFPErcj9P6RSsp3PFHumAtC/b
; Q4+VCaVoaLG8t9NRjsmptIdPO1kLHGiG5GMqamBVqU/1LjBFwFA05ED713W1sFMkaDTAqkiXI+uzz0
; /nmVlWNhwMt9OfmQDpuRwltFA6uklzBBqlLZUAwJe1MbiBEJbbKx47RAw/vY1QlOv9NmfEt6t7yPPY
; NrurYyuE/YxypW7SiFqSgpEN8/SJRzw+GJcsdcQct9MaQF5EMwIA8ePNjERZyTYC/xRvDFMzkh9pZh
; RHSTQlY5cfjm56WUY1l5vUdkjIZpr4NPC8xJlFMD4rkOx8KCJ9ixn9bYgPw/MCKhbp980V86efJxMs
; Eu5Qgyk6A1L/iMjGUguiWIf9obo2T8chLsNfc09TkN5b4LpXcmYzTIIavdVkGJaYE8qe7TAh1LA95P
; 69NPP/0ZhLSQvR5rEU979IQS7KmNT2OjSiXKVTbfRKK8RUZ2orwT0U3DG0nKUNjgk2tLQe85a+tnhw
; 4FGeP4jtBJoTFSIHgdmKN0w+FYCkjlvkBQQvKhlGDP6aeV+wI3b745v9vg8RTLKOFBVGzW1UY3o2po
; 6p4rvZGF03sLwTGRKP/3w4ef8FxhKNdB2eX4M7RXnTPKHUsNqZ8Wkg9Ho9HvkDsSi+VCgh0GVlmR6f
; jGULoBLQrRLdvrUPpeVZt1IqymJqNA7ymPIPZ7mmsrNPAJJgHGwlXw7mCynM7s4IYDDnSDw7FskAZW
; Qbnv7du3P84hH+ILsvHyy3/QHlhV8jPzlpHkQVS2FsmVofq8MvppLYNONGSMhtlEOe2OC1esYSn92T
; 0O1jue63CsHDCkRXkjUj8tNCK8pn23ydvRo0+qy33XjElocyC6tXodpZue6n0EjF6tRxDUiWSgKr1N
; bb2PhnCinIej6AFLejcuX768c/r06RO8RNfLcx0rA85gpyEt2pfn/Pnzj0Ks2qaBVeSF1twMg5tGQY
; 6gWAbwIAyMR2hjNHlePMFuxYPhRtdY7ykjCH2sfiZ0z+WJcmngE4a02OWMcsf+QKif1kcfffRrNCQQ
; z6XJ9lB33+p+Wj2mxu0NSTL7bCTrWZLpYDMEOdZETdhwYfIh3o+BrInRtdZ7QsZo+B+vA5PfKVIg9T
; bowCfaBNGNh2PfIdZPC8mHYESgSiuWYH+vIKSFYROLuv4pOYRdrLlhSSErqxP1RN7ec+oiw4h8SD0C
; M72TsFjICPI+VthSHf/MSZTje4EVVm44HPsWUj8tYLAD+RCS7LTcN5Rgh5/J6aclbbQmGzz/PE2uRa
; gMVntjjBE1O5AoUwn2Zhkd9E7/bjSE+1hBSAqu2LRAmuuAwhPgVbnX4XDsgTPYkXxIXXWJNIWGJdVP
; K5ow7UhCq5FRkijX2Bhz7kNFRsw4sHLfao7KvPU+/uzffu97T/7vt771LGQYaL6DJ8p5rgP6WI3zgz
; /GLg/ex8rh2EOonxZvEY8JdunExvtplWx2tRtjKmHaIqPEePCNs/Q+ir5fw+ZbJKMypFWk98qcS0oG
; JMpPj9di6PAjrV80GlKiXOJ2uNfhcBCEQlrYIp4mEUPxYvRG7tQYhMLN96taGanNVyEfULIxJj0Cjf
; uvLJ2Nhu5avxPXidJ9j4ZvEuXUCMDhBzzqGHEW/g3WOoSquPHwkJXDkQGpRfz7779/Hl6qUD8tHhoA
; I3P929/+WnNgVetmmLMJVXkdlRtd7s/kGIYeMmLPREVGwrDTIozQz0iJctrYMMQq5yW7e1WI3gDR4a
; iBVO4L3ojUT4v3DKIX76elssE35gBCm+/MaVtLhrQxKhjBqefSa0qk4I2oy6jQ+2gIJ8oF3kbWtEA3
; Hg5HI6g3EiIfUq9EeklLy31Dm6+q8aCbE3At4LIiBQ79SZRWMqYS7MAbOXHikXpZLtd7wtBujdfWXz
; ///J9SifJQSIuTAr2PlcOhiFA/LcyLwLwDSj7MSbAXbYx741lVNym66facFrjMJEr63PCZaXprkt4j
; nz0a/sfrQEPBpwWmQqzI66C5Di/PdTiMwPtpgSGBkNb9+/evwZWbYL/7wgt/zN5E1hiZTum0K+Y6DI
; luU96BJdubEPasDNUUUbMgwV71vAI5ntEgTwvECqpQohy5HzgtEA4/8PPQx8pDVg6HMSiDHQwIGJJ7
; 9+69C+z1ra2tT2MJdlpvn+ynhaESgSCmwh3oPS1wDjJaSopLZWiF/0Jl2fh3UJ77fSHXgWsLjEOM+E
; rDVXDYGeNtNxwOR0fwBPv169d/OL4uYD+tWIKdTnT714MHn23nblRKG2P2ZqfgjYQ2Q00Zk3uK3Iva
; lMi1BMGx0RtJybg5/rfXhGmB0trCFiUh40GnBbrxcDjmgFg/LVqpFRvKwxPs2SfzmsFFFeW55oS9od
; 4b6SYj1yAUDqya+r2MRLnUWj3Wxwr+TUqU01wH/umGw+GYAziDHcmHt2/f3sDcCA7liTWre//48cf/
; ZUSmaz4dlxIca8pzawziIsoYyvpp5ZbnSh5EDikQfgbyHMgBcUa5w7GA4P20xi/sT+7evbtrQGgrlF
; BlDLzon2xs3NEcWFXrddRuvhp5jSwZjSGp3BBhy73wZ1878ImW5/LW6qFpgfTnYF3B+hvjKk+Uex8r
; h2OBwBPsYERu3bp1DsslaW4kRDyEq7rcl/MgtIxHxqanYTz4Bm4uI2R0le+D62BiBAO/l0qUcz4HDY
; 8GPJVfenmuw7EE4P200IhASAvLfPEEyWPTNAlaO7Bqd3NCfoIRKZBuvhoeQXKDV2athwyGqvHgMlAf
; J048SnE7chPludMCafdcNx4OxxKAMtjRG9nZ2bmIhEMkH6JBCYa2CsbnTm1UPaYFJohuajKMSJQTGX
; sTFk1loGFHxr9gqLCPlTQtUMqhYaiKkgKhlJznOjxR7nAsIWLeyKNHjzYwPxJLsMPfv3P48JOsgVUs
; UW51op7yCJS5FjP31Ivg2ItEKehpNMz2scK8GC/HlQ4Z2A0BLmj46d1zHY4VguSNfP755+u5CXb4t5
; 9+97tPpX5ayVyHBYNdyoEohrG65VmE5La20Q2SD/f09dvTpx+GBj7FDIhECoREOXCSPFHucKwYeLnv
; 3bt3z8QS7DR0EeqnVZIo16qQmrcMDY8nS4YGiTJRYbVx5sxDyu0I9bHiIaxA8cU7WAHoXofDsYLgDH
; bwROAKJdhDU+PAG3lQS1ir2BiLDEPt5hvwCILfqZbtXZCMbyIfJowHnRaYM/AJ8x1S12ckBnqi3OHY
; B4gl2MfG5GOIZce6+qKR+ezcuXv3K4lu5mS6FWGil3g8ORVplwXDQXkdqVAmTguEn/Vch8OxTyEl2I
; Hode/evcvUG6GhC17/D0Zm4+WX/6A5sGpq4yzwCIKfkSIGtpbn9iI4JgxDLqOckvyoHlHfoXYl/Gdh
; QqYbD4djnyNV7oshCyl0gdeFo0efvKfNYNdMJEvdZTskq3M8glYZORyVt597bqZ6SiIDSl7JjK4vXD
; jr4SqHwzEBT7BL5MOYAcET6y80GOxLTNibITjOWcZo+J9ch1SijVyPmPGgw5481+FwOKKIJdgh7h3a
; bDiDvaaf1q7hAMKeAQ9iSgYQ6Sw2drrBg4w5kyhHwzchK6qjUOt1GqLCYU9Y4v3WW299hH2sqPHw8l
; yHwzEFqZ8WhLSwoyr1RGJtvLcOHXpaxGA39g56y5h4ChYy0HAIIcBQHyucFhgbNEYZ5Tgu2RPlDoej
; CFKCfeyJnOflvrH2FseOHXua6qcVzBFosstDOYIeBMfOJMrRMMsop14Hehoho0+T6dgE0Y2Hw+GoAk
; 2wA8M4lGAPhUfg4gOrUpuhtDFqb7ilP5PtERjJyEmU7xw+HGSMU0PPpwVKpEDMdTgp0OFwNAG9ETpn
; ROruCyQ0CJFIp1v4u0mCPWMz1Nh8i8mHRsO0pmQYkChHwzQpEI2FNFaWG5bQtEA0GqBrNx4Oh6MZr7
; 766t9K5b6QXH/w4MFmjISGRuTSyZOPHx45Ut7ZtmDzzfEIgr9bMjq2slpMk3wI5bkw8EnqSwVXTBcY
; psLcFk2Uex8rh8OhDlrui0ZkNBq9Bk0ZQ/20JAa7xsCq1s15njJSHk9KBiTKea6DTwEM5agkYzP++d
; c91+FwOMwhJdilflqYrA1NPawdWCVuvthdVqvqaYEJjqMhL1EulVlL/+bTAh0OR3fkMNhpfyW+mU0q
; fwoGVkmbr/amLm3m3WQkQmg/O3jwWSxRzkNU1MugbftproNOC3TD4XA4uiE1PhdDW2hQQl1eIcFe1U
; +rx0TCHtMCEyTKEfE6aFUVJwlK3A/K7UBj7twOh8OxMAh5IzD1EBLsePqNTbaDBPutl156WnJq3/1/
; Za7FlAziEZjMXR+mW7dIng4myrnRRWMQmiRJc044LVDidcABYHA4HI55Quqn9fnnn78tJdhDid2cfl
; pBMp1imGmeMtAgjgY514GeBRA1+ezyWKJ8a2vrLOV1uNfhcDgWDrSf1qeffvozmmCncXjaIp56JqF+
; Wjk5gmZvJKc8t8O0wJvjz4ZpgSFDG5oWKLVq3+Po/NgT5Q6HYykQ6qclJdhjRDdMsJee/C0Ie60/n2
; MEoTyXD3yijPEYr0Oa6YG5DtpB1w2Hw+FYeMQS7BDWgsmHsOmFGjLipnl1fBJ/UJMoL53kVxOaKiU4
; ZpTnhrrjSqEqKd8BxE74HU+UOxyOpYeUYP/ss89+HeqnJcXxr62v39McWJXrEah4IxlhsTcivI69po
; bJZ+S8DofDsZJIlfvy7r7Sxqg1sCpr06+5BI+nlhRI+1jxnEbsGfnAJ4fDsbKQBlbx3Ahns2sNrKKk
; Q6uph6XTAv9lfC+5iXIa0uLPyPtYORyOfQEpwQ7eCGyK29vbt4CvgAYllmCv6adlajyoDCA4BmTQPl
; ZSa/VYopySAnHcrOc6HA7HvkIopPXhhx+uA/kQkuwpohx2990u2dgp+dCAwZ4iOI4CISvMc+QkynHc
; LBhaNx4Oh2PfgifYNzY2TuQk2GkLj1Q/rVgoSY1dvtfMUfoslP9GgBSIeY7QtMBQohw4Nm44HA7Hvg
; b1Ri5fvnw8N8HOyYdSgj0nUd6aTM/Jdfz74cMzjHGpjxWGtPBnQ4lyNLpuPBwOh2PI6+4Lf8LUw1CY
; ZzI+N+IRBD2IGvJhIp+yNf4u544enaqiChlBesE9Ug8ME+VSHytPlDscDscg99PCBDvkRrAVSixXAJ
; vvvUuX7lgMrCrxOmj3XN6XKmYEKf8DSIHw857rcDgcjkxI5b537959TxpYRTdfOpGvJMFe4o3UcDvo
; fA4ekuPhK5bruMfLc914OBwORwI5IS2aSJeIh3C1DqyaMhyJPlbfjyTKQ98z9PdICnTD4XA4HBXIYb
; DjtD2aL5AS7C3eSI7XcUSYFhhK+FNPIzYt0I2Hw+FwNCLmjcDAKiQfxrr7ThLspQYESIGRaYEw8ImX
; 5GKiPNYoEvIglBToDRAdDofDCKEE+xdffHEFEuyQcA4NrKKb9sbLL/8hJ6TFvQ7+/6NBJgWC4QBDlk
; MKxLYkYAAvXLhw1o2Hw+FwGIIn2B8+fHj+3r17l/nAqlg4KdVPKzUtEAY+/X2kgy4lB/JkOk+Ur6+v
; b25tbf0bz3d4ea7D4XAYIDawShqfy6cehvppTRLlAcMCifKPDh9+EjJQIaMldc+lISsnBTocDkdHlC
; TYQ+Ek7O67PeSV555m0wLRMMVIgXRaIE30e8jK4XA45oxQgh0aMkJuIdRPi27wMLDq1pEjj0O5EdrH
; SpoWGOsaTKutIE/jXofD4XAsECRv5Pr16z8O9dOSNngwBryf1iiSKMffSeVceBNE9zocDodjAZEiH6
; bIezTBDuW5f/3888lEeSikRQ0M9rGiXof3sXI4HI4FAy335QOrMMHODYrkmUjlwLFEOYapqMfj3A6H
; w+FYMtCQFu2nBSEtmHoI+RE0KLEEO3oUOYlyOi0QOSnj6x03Hg6Hw7GEkEJao9HoR0A8BAY7eiEhw4
; DkQ/AkQuRE6oHgtMAxznqi3OFwOJYcPMEOUw9/97vf/Tw3wQ5/SsOfQolyKM8dJ/B/6F6Hw+FwrAhq
; uvtK7eJ5olxqgIieBxiuweFwOBzLj9jAKvRG0JikmiDSEl5PlDscDsc+QSjBDrkRIB9KA6toHyskEI
; 7DYe9KA5+8PNfhcDhWGLF+WjkDq9zrcDgcjn2MnH5anHHuxsPhcDgcE6QS7Fju64bD4XA4HDOIeSNg
; QNx4OBwOhyMKKcEOXgk1HN7HyrHf8d/SSge/IHIZKgAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.60mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.55mm


M140 S110 ; set bed temperature
M104 S245 ; set temperature
;TYPE:Custom
print_start EXT_TEMP=245 BED_TEMP=110
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)
; at 240C: 0.06
; at 255C: 0.064
; at 270C: 0.044

;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06
;SET_PRESSURE_ADVANCE ADVANCE=0.06
; Still seems too much.  Testing a bit less.
SET_PRESSURE_ADVANCE ADVANCE=0.04
M109 S245 ; set temperature and wait for it to be reached
M190 S110 ; set bed temperature and wait for it to be reached
;LAYER_CHANGE
;Z:0.24
;HEIGHT:0.24
G1 Z0.24 F12000
G1 E-1.25 F1800
M204 P2000
G1 Z0.38 F12000
G1 X82.5 Y162.175
G1 Z0.24
G1 E0 F1800
;TYPE:External perimeter
;WIDTH:0.55
G1 F2400
G1 X5.325 Y162.175 E3.5316
G1 X5.325 Y7.825 E10.59479
G1 X159.675 Y7.825 E17.65798
G1 X159.675 Y162.175 E24.72117
G1 X82.56 Y162.175 E28.25002
;WIPE_START
M204 P4000
G1 X82.3 Y161.829 F12000
;WIPE_END
;LAYER_CHANGE
;Z:0.44
;HEIGHT:0.2
G1 Z0.44 F12000
M104 S235 ; set temperature
M140 S115 ; set bed temperature
M204 P2000
G1 X82.5 Y162.375
;WIDTH:0.45
G1 F7200
G1 X5.125 Y162.375 E30.65955
G1 X5.125 Y7.625 E35.47861
G1 X159.875 Y7.625 E40.29766
G1 X159.875 Y162.375 E45.11672
G1 X82.56 Y162.375 E47.52437
;WIPE_START
M204 P4000
G1 X82.3 Y162.029 F12000
;WIPE_END
G92 E0
G1 E-1.25 F1800
G1 Z0.58 F12000
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
print_end    ;end script from macro
; filament used [mm] = 47.52
; filament used [cm3] = 0.11
; filament used [g] = 0.14
; filament cost = 0.00
; total filament used [g] = 0.14
; total filament cost = 0.00
; total layers count = 2
; estimated printing time (normal mode) = 22s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,165x0,165x170,0x170
; bed_temperature = 115
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonicgapfill
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0
; bridge_acceleration = 1500
; bridge_angle = 0
; bridge_fan_speed = 70
; bridge_flow_ratio = 100%
; bridge_internal_fan_speed = -1
; bridge_overlap = 100%
; bridge_overlap_min = 80%
; bridge_speed = 40
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 0
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 4000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = print_end    ;end script from macro
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 0
; external_perimeter_fan_speed = 80
; external_perimeter_overlap = 100%
; external_perimeter_speed = 120
; external_perimeters_first = 1
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 0.92
; extrusion_spacing = 
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 0
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #FF0000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 25
; filament_custom_variables = ""
; filament_density = 1.25
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 0
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Tuned 2020-12-27 to PA=0.08 on both 0.3 and 0.2 layers."
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = f0-abs-kvp
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 40%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 94%
; first_layer_acceleration = 2000
; first_layer_bed_temperature = 110
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0.55
; first_layer_flow_ratio = 100%
; first_layer_height = 0.24
; first_layer_infill_speed = 60
; first_layer_min_speed = 0
; first_layer_size_compensation = -0.15
; first_layer_size_compensation_layers = 1
; first_layer_speed = 40
; first_layer_temperature = 245
; full_fan_speed_layer = 0
; gap_fill = 1
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 80
; gcode_comments = 0
; gcode_filename_illegal_char = 
; gcode_flavor = sprinter
; gcode_label_objects = 0
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 4000
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autosmall
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.6
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 20%
; infill_speed = 150
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.2
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = ignore
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 0
; max_gcode_per_second = 1500
; max_layer_height = 0
; max_print_height = 120
; max_print_speed = 250
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 50
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 10
; min_skirt_length = 5
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = bridges
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 50%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 2000
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 150
; perimeters = 4
; physical_printer_settings_id = f0
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = v0-abs
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = dz
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0
; resolution_internal = 0.2
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 1.25
; retract_length_toolchange = 10
; retract_lift = 0.14
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 30
; seam_angle_cost = 100%
; seam_gap = 15%
; seam_position = rear
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 1
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 0
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 4
; small_perimeter_max_length = 10
; small_perimeter_min_length = 6
; small_perimeter_speed = 40
; solid_fill_pattern = monotonic
; solid_infill_below_area = 6
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 150
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)\n; at 240C: 0.06\n; at 255C: 0.064\n; at 270C: 0.044\n\n;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06\n;SET_PRESSURE_ADVANCE ADVANCE=0.06\n; Still seems too much.  Testing a bit less.\nSET_PRESSURE_ADVANCE ADVANCE=0.04"
; start_gcode = print_start EXT_TEMP=[first_layer_temperature] BED_TEMP=[first_layer_bed_temperature]
; start_gcode_manual = 0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = honeycomb
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 235
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 0
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 12
; thumbnails = 32x32,400x300
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonicgapfill
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 60
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 1500
; travel_speed = 200
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0.1
; z_offset = 0
; z_step = 0.005
