; generated by SuperSlicer 2.3.57 on 2022-07-23 at 07:01:58 UTC


;
; thumbnail begin 32x32 1548
; iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAET0lEQVR4AdWXS08bVxTH51t0SfdI3X
; aHuumGRbdsyq5dsOmiCxSpSERVJBypNiURODIePwDbdWzjF7bHb48dz3iIH/cjdX6uDrpB1KQNBOVK
; V3dm7rnn8T//c65tGF/q2NjY+MZ4yrG3t/fj7u7u1tra2lfGU4xkMvnMsqwAc319/Wvjcw2gPz4+/i
; WXy+1PJpOTwWBwVK1WX2xtbX1nPNbY3t7+HqgxHggEfrZt+8hxnJg1q6VTs2TJf460Wq2XBwcHPz0K
; GkRMlOl0+rfRaBQezuxEXV2lSyr/NqpOajxP3k9OBQ24AUeMhxhETb59w3+6rmtiPKcyhYoqZmVNqt
; PqiTpsjmbDuJ+WN6DBmU8iKIeBm+iJ2pt60YHqJ2Raqp4i8oLK5lk7qnXeV92ku/CdvB6e9nq9Q9DY
; 3Nz89j8ZBrqdnZ0fMFwsFn8fj8dviDqjzovMK1X+a6zexUZqGMcREGCVd2RApjmvp3zHX0tKPtoBDF
; NaPrGOPc8zGz7RzpRZQSlQM4lYR4PocYw9Xc5a1FP2ZBDt9/tBHFlJUGG4lBdRA2lZXWaFcChnJUr2
; POVFbTVYOtBS1oXsszJFbjqfRlaWq9R2rVYLSHnpUaJEJx7GMEr+eWf/PrnSrPDWJ3EYdD8o10gk8i
; vG/VzfRM0BvEcB+SZKVpTJu8hRhsjhAN8lJfLOnsi1Z80Lx3Nu0IBrht9UQpSXM3Niemmxcohckl9X
; uaaQj30QkhU5QYK0IMdkHwdkFbnRfBi/vr5eomH4HsUcNTYljxAOpUI8yo09RzlmXVUzPDMlz0I8Jn
; zBMHICvy4HquhGp7MYxyhXw/bsONDrpSTEE4UokoaD8qGy4wI1ygVyJuf4psthUOfKUs67SttDO2lU
; KpUXfj5C7tQ1pcZ1Z4Tdesfjm+yL0lVy6EQOR6mSjtu+8O0W/I756qbPR6PRvcFoYLoLxwRuCMRh6X
; T6CpTsSRmiXKKUyrhLrjW3Llr9ZqrRaBxR8rTrZefDCaqBHlCv1/8YvP8nIolQiCTEE76QIr0TIqsT
; T5BBrjmxUkTt63+FPSZO3PR8HGEtFArPTdN8Xu6WchwGja5qLw0SJUp5J10QVW5D4QRTf0euObLS2W
; z2JbcpNuSOWToggztfnEAwFArtW93Gmb3oJyBTT3XOcEYMpFSipHdGMSrlyjNRdzqdFMYxiH6Zd/6m
; 5KM4EQwGd3Dk8vIyaE3rH3RFYbreN3BkWV6+k8vK8YmWz+dfZzKZfUF4pXEZpAQ05BBOhMPhZ443jn
; ZnnXOQgFCUmRBO73zlaTE7dIYJiAbJBO57Dd+HBuVaLpcPx9Nx7PaVLAQsTvJ5iNZut08+CvL7hqAh
; lQIalKv9zk72590kTgghe273XHItkf9vw6vQwAnK1b9DEtz3QrTb5fVgxmXcVa4QFKLhlEAuDjzKHx
; Y9JUIuPeIHj/rfhqTk9vys/xd1NJ70j+qnGv8b3fIIbSRV+v0AAAAASUVORK5CYII=
; thumbnail end
;

;
; thumbnail begin 400x300 18044
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAA0o0lEQVR4Ae19329d13HuAZL7eoHg/i
; zuQy4cXAQXudexc5teNDXSJnCbtg4MJEiaoq1jt7EKW3Aj0wZsqTHkWm5tybRFU7JMibJDiZL1kxYF
; KpTVWHIhSyqK6IUE/MQnPfuJ/4HKj9E44/Gstfc5Z/9Ya+/vAwaUjo7Iwz3n7Fkz38w3gwFBEJv45j
; e/efdzzz33Vw899NAffvGLX/xvA4IgCIIoggSP3bt3T+3atesZ/BmPDQiCIAjCgwQOCR5vvPHGh7Dp
; 6ek9ko0MCIIgCEJDggcyDgkcjz322K2dO3eu4s8zMzPzElxY0iIIgiAGCAbILPbs2bNFsg4Eje9///
; vr9913320Y/ixBhSUtgiAI4lMlq6WlpQPvvPPORWQdEji0IYhINvL222/vI8FOEATRU2iiHEHhvffe
; O40AYrMPaxJE9u7de2pqaup5ZiMEQRA9gUeUI+uQEpXmP7zggcclG9nIRC5vPPcgsxGCIIiOw2YdOl
; BonkMMQQL/JgHGBhX8HUEE2Qi5EYIgiA5CiHIdPCQ4hEpUYhtlqhuh5+rAg0AyMzOzg+2+BEEQHYFu
; z0WmECpP2cxCggJ4kaL/o5+PAMWSFkEQRKaQMpJXskI2EcsoJCDI8+T/PXPsydVHXvuLW5Zg9/gTlr
; QIgiAyxYEDB7bNz89vt0S5DRA2GAg5bp/7o6Xv3vofq//hNgx/xmNe4JDvyXZfgiCIDIET/7lz517A
; XAdac1FW8spPNliEiPL/89L/vC3BQ+x3P/zf63c6sIJdW/L9mI0QBEEkDjsUKHMdZfiLl19++aYta3
; mBwxrKWrHvr7MR6mkRBEEkCEuU6+Bhy0telmCzjzLBw5a0yhDseG1WT4ulLYIgiJbgtefa8pJXahIe
; RN/sQZKjPFU2eOiSVoxgt5wJAh20t7Zu3fogXvuAIAiCaA6hiXLcuEPBQzKBDY5kcZSSVdlsxCPjbU
; nr6NGjU+BqQPYzCyEIgmgIsYlybxhQDGUtXd6SjKGK4KGzkZeXdwWHD/E65XUsLy/PnT9/fpIEO0EQ
; RM3wso7YjdrLPvTfX1va8+H3Vr59q6rgYQn22MyIZEIIJBw+JAiCqBGhoUCdSYRkRjxDuel3Vr+0/s
; TKI6sw/LnqIIKfIeR96HVINuQR7ARBEMQYCOlYSdAI8Q1y4rcEth4KFEMW8vLKzlqykW1Xt6zO/+LI
; xRixrwOMSMSz3ZcgCGIMSNaBjqUiHSs9Xe4NBeJxL3iIIQNBEKkyG9GB6ZH3f7gWCiAOd0OJeIIgiF
; GhS1ZCfBeJICJI4KTvzXx8aeE/lbrpI4CMm41I4IDpYASCXYYPiybYsYOdE+wEQRBDwCPKhSeIbQvU
; pSydjYzSYSUBAMFknKyjiBsJBULdRUaCnSAIogRC7bmhYUBvYK9syarIhGC3WUSZrKNM9oJsxAYR+3
; tQT4sgCKIAOFmHhgLtAJ7uwNJEedVDgcNkFOOQ8NLuGxJz1AS7BBES7ARBEIPhFj7pIAKuA9xIHRPl
; oWzEEuw6SxmHM3n8+o8/gqBjjN+R331hYeEdtvsSBNF72JJVjOPwTuTSGouA89t/fXdponxU08FC8y
; RVdG2F9LS8IUSWtAiC6C1COlZF2wI1Ua6zkXG4jlGykbdWZi7uW3nlch1zI1bdN1S+I8FOEETvUKRj
; JSftmLKtfqzJ4CFZB4LHsytP3CxLsI+SjUigtA0EmvthNkIQRC8ggQPqsx5RHso0miDKhwkeOuuoc4
; IdtnNhx81Y95nOTnBNMXDJbIQgiE5BE+Ugvj05dc9ALGMGpAmiPGRFRHkTelqxYGuzERLsBEF0Ap6O
; FYKHJr9jN0W7WwNEeVOBQ2cYZQYK68xGhiHYdbsvS1oEQWQJTZTr9lyPENY3xtA8RJNcx6gBoQ49LZ
; uNhIYocQ1tSYsEO0EQ2aEsUW7r+yECvcmS1bAT5Z5VMRtSlI1MTEyshbI4EuwEQWSH2JrZEFEuAURK
; W6kR5eN+r1H0tMpY0fChXF9c06WlpQPMRgiCSBahhU9FRLldrCQZSG5Zh2d1E+yenpaX5SGIzM7OLj
; EbIQgiKcQWPpUlyosWPjURPOpqxa37Z4hEvMcjeUY9LYIgkkAZHStvurwO9dxRrE6uwlpTBLttUtDX
; 2RLsbPclCKIVSPCYnp7eo0tPsXKKqM7azqsmdKy8jKCum3lbQevbv7r3Y72wytMWI8FOEERrsEQ5Bg
; OLlGTlxiXbArtClFcRwOr4/kULq9juSxBE4/CI8jLbAnXJatxtgePetNsOHmLDLqwa1mIEu+VJuD6X
; IIjaEGvPDdXbLVGuH/vWW7/TaNkohayjrdcWItjFJ7rdV2cjA4IgiHGhiXIvSITkxkODbinpWKViTe
; hp6W43rzNOfCh6WhBmZEmLIIiREWrPLTN3gMFAfaPqE1E+7muui2CHum9sYZf4EGXJjbLWDpa0CIIY
; Gl7JqsxQoNyARCxR/l8fifJRrQ09Le8QgCBCgp0giKEQ0rHy2m9DrbptbQtMjSgfJ4jUTbBrdV+9Jt
; iuC0ZJa2pq6nlmIwRBBFFGxyo0Xa6XP5Eoz+d3AsGOFuxQIwTbfQmCKIQEjxMnTrwa6qaypLleudo2
; Ud6FrCP2+9WtpxXrorPDh3LIYDZCED2H1bGSbYExolUMJ1eUOfRzyXXk+buKnlZMt0yyT3Aj1NMiiJ
; 7D07HSirhFRKvdFth08MihPbdqS4FgZ0mLIHqOEFFeZlugR6S30Z5bF8GcgzWxsCrmdwkmkIifnJzc
; xpIWQfQAZYhyTwpccx5tcR06ePQp6yi6FnXqaQnB7mUllmDH4CGzEYLoKCR4bHzgD5YlyuV54Eba5D
; u60p5btdXd7ovhQ7slMlTaWlhYeId6WgTRMeBEaLOOmPS6J2+hje256VnTelqxbJV6WgTRAeAD/MAD
; D/x/b+GTJr/LEOVtDAXmomOVijWlp1VU6rTtvixpEUSGmJ+f337u3LkXNkoQ+0I6VsJteISpfh50rE
; CuNnUzzFHHKhWrm2B/7M2frMW2HkpgoUQ8QWQI4ToQPJaWlg54/EVourztoUAdPJh1jG663beO749s
; JMajcYKdIDKEbs9F4ICVme2QfRB4TlvBg0R59UGkbj2tIi6N63MJIgN47bk6cNg6tf2Q6/ID1XO7ZW
; 0R7HIw0fNFNhthMCGIlhEaCvSCh7bQwqcmu6xIlDd7nZsm2L3HkI3Mzs4+hRIrZkcGBEE0D6tjZYny
; WPBAdgKzC5+avKnVPQhHC1/zOifYcTAJyf7jMbzvUFpdXl6eQhBhFkIQDUOXrHR7bmwYUAxiibq8he
; f80Uu/z9mOnljdelqPvP/DtRixLtsqEUTQ5EGCnSAahFeyim0LLCpnbbu6pbESEnWs0rEm9bS896Bk
; IiTYCaIBxHSsYtsCQ5mIHgqsu+0TxqwjPWtST8szZCNs9yWImhEiykPzHCEyUz6s3kR5XW2fbM9N2+
; oi2MXv+3/16uVQR6C0jbPdlyBqgNaxwrZAnNhiS3/0dLluzx1mrqPKTIFZRz5Wt9/R7htrKZcDEN7j
; XFhFEGPCLnySocCiAIJ/lxPfqOq5VZxK2Z6bn43r96L1wkUT7HqoVUpa1NMiiCHhlaxkUjxGmmsuRL
; gPkJmjLnwa5VRKHav8bZTgX5ZPkfW5MXVfLcrIkhZBlESMKPeIcPkQhtR1q5goH6btkyWr7tgwBPso
; fveGD/XfqadFEEOgDFHutUOGtsZVLUcSO5WSKO+mFTVWjNuWjWxkamrqRqykpQn2mZmZHcxGCEJBZx
; 1v3NkWGOM59MkMZS3wHbqFt04dK+9Uyqyj++b5uEq/71zYcTMmyigEO97rXFhFEHegiXKvNDXscGAT
; OlZyKt238splEuX9MfH7Cyvbb9SRbdqSVuy9zoVVRK8R07Eqsy1Q/k2eC1KyyZsJbhxvrcxcRBBh8O
; iPid/bnGDXGzJJsBO9A97sUCH1iPJQR5U3FFgX11HmJiI3kLpVXmlpmFVNbkJPS3cdWk6QBDvRS0jJ
; CiJyMqtRxHdootyWtlJZ+MRSVnct1pZd98IqGT4sQ7BPTk5uYzZCdBK2PVeGAkP6VXawCgFEz36kuP
; CJ8uzdsxT8jiBS5pClhw+ZjRCdgdeea7WBYuShFkzE35sMHkWTxd7z6zyV0pqxYduy6y5lIhvxhmc1
; X6izETmsMRshskWIKNenppAu0Kg6VnXcREYpS7G1N19L1e8hgt0OH1qCne2+RHawOlahLMNOl2Ooyh
; NMbDp4VMFpkGDPy6paL1w3wS4S8bEdOOpzdRANKyxpEdmgzER5qM8dpS0dQLBmdlQdq1GsjoVPzEbS
; tzp4jDobK779q3s/1tlILIgsLCy8g4McAglLWkSy8HSsRFo9RpJLHddmI00MBXo3kTo+8HWfSmlp+r
; 2JhVVlhw+np6f3kGAnkkQs64htCwwR5d7Cp7pvIE1kCSTY07Gm/F53Y4Um2L3AISQ71X2J5FB2KNCb
; Ls+dKB/3Z7Ldtz1r0+91/UxvYVUZdd8BQbQByTqOHz++C3XWMtsC8e9NqefGrCrCdNyfz5JWs9Zktt
; mG38surKKeFtEqdHvuuXPnFmGjBpC2iPIUbt4k2Pt5rZts9y0KIixpEY3BI8olIOiaq33zSn+6DjB4
; XpeI8lGNBHv9lqLUjPZ7Hd+/iGAXblLafUmwE7WiiCgPbQtMQQSx7dJFrje53C2lbNOzJgh2yUZCKt
; ck2IlaEVsz62UZdltgH4nyKm54qb/WXK5lTn6v67ViYVWsxGyWtO1jNkJUgmGHAnV9FUOBTW4LtDas
; jlUqRj2t8SyHbDPm9zoJ9jKbPhFoSLATY8HTsbKlqRhRbocCm5zr0DeRnE/yJNj7ec3aINhDGz6pp0
; UMDV2ysjpWsW2BluuQ57YVPLpw42W773DXqUt+r1tPK8Zf6koCJeKJ0pDBwKKSlbct0Ou+yl3HKhVj
; NlJ8bboYZOsMipsT7BvcSKj5hQQ7URo665BtgUVcB95oKQwF6ptIl2+wbPftp9+b0NOKcZsk2IkoLF
; FedlugnE5ECLENojxXwnRUI8Heb783vbDKNscIwc5shNgkyr323Jiejg4eVmeHXAd/d/7uef/u0NMK
; Eez4ahdWya6RAdEvxBY+6ZTVbgtMYSiwa4TpuNehLyWtXNuyc/O7R7Dbzzv1tHoMb7bDK1XZIIKyFj
; gP/dw+61ilYn3iAdhE8BtrgmCPlbUkuMzMzMxDUJUlrY6j7ER5aLocAUT/HxLl6ViXCXb6vfjaNK2n
; ZQ+Z4EbY7ttByInAyzrKbAvURHlb2wL7RpiOY10q7XW5LbtKa3JhldeZpY0Ee8dw4MCBbfPz89v1bI
; dd6hQqYVmiHH8mUZ6+cQq/336vm2APbT3kwqqOASeAc+fOvXD+/PlJtOaGxNTsdDmJ8vwt13ZfZpvV
; +L2uUuYj7/9wrahLUw8fkmDPEFrHCkOBCB6y8KmIFANJbp8DorzJD0EXTtCpGBVp6feqvzdKWrI+Nz
; Z8aPW0WNLKAFbHSoYCixY+yalhYmJiTWcjJMrzt9TbfZlt1nddm9LTihHsIT0tZiWJwSPKbfDwUk+P
; B2l6WyBLF/VbijdptmU35/e6F1Z5B1LNmWiCfevWrQ/i64BoH7H23FDw0AHGlqyYdXTX6l6jSr+naU
; 21+3qrq23X1pkzZw6Dm0VzD7OQllG08MlrtZO+bV3eaqNkxayjHWubYKff2/V7nXpa4FpDZS08jvsN
; 7juXLl16G8095EZagrfwKUSQe213CCD6768t7Wn0VMrTZ/vWhg/o9277vczCKjm8wriwqgWEdKzKdk
; VYQ/rZ5KmUhGk61hTBTqI8Pb83QbCHNh3CkK1ogp3tvg2gSMcqNF0uC590SQuteDgxaMfXeTohYZqu
; NeX3pn4fWjmrM6hvu7pldf4XRy7aaodt5OEEewOQwBGaKA91QHgraIuk1+s4lbJ0kb7VcSql39O3qg
; O8zTZlYZVnlmCnnlYN0FmHEN9lRBAl8o86UV7Fh5+EaX5WxamUfs/Lqiphh6oMqHSUnWCHui+zkQrg
; tedK11SZbYFi8txROqzGafvk6TNfG+dUSr/n7/dRfFfm/6JsHlPDCA0fDojhECPKy0TxKrcFDns6IW
; HaDRu2lMmsg34v43dvgt3et7iwagx47bmSbYS2BcrEp6djVdXCpzInDBLl3bNh/M7AQb+XMd3uG+og
; 1QdmlrRKYJiFT15fNYQQ654oj51OeBPprsX8zmyz2373DoRVrRd+/PqPP7L3rdAEO4RhSbAHoInyEP
; kdmu3A8+X/SAZS90S5DhYsXfTHdLBgttkPsyXsqru2QsOH3mGZ7b4GoaxDk98xwkmep4cCm3xjvbUy
; c3HfyiuX2ePfH8MNRPzOA0P//F7XQVEWVsWGn9nuq1CkYxUSJvNqhk1vC9Qp7LMrT9xk9tEPk9Mngo
; f4ndlHv/xep3IB7mFyMC5SD+8twS46VlCjLNKxkhqg/LtdM9tEuSr0ZtIBo+q0lpaexfzOwwP9XpVt
; 7mBf2HEz1m3qLazqRbuvLlktLy/PgfyO9UWLgWhKXXo91zWqtLgVtWWnvrCKNpoVcZtN6GmVKeP3pq
; RlS1aenHqIRNJ8hzy3qvbcYd9MRW8Wnkq7Y8MQ5fR79/xexpd1duGRYB+EifLQPIctX9ng0uSmwGHf
; TGI8leZvo/qdnVn52qhDwE0trPIO1lrzr3PZSBFRHiKLQsM1uS184oxAflal3xlE8vP7qMG/7hL2Jj
; eiCHavatMZdV9EvrJDgXa6HGUtzHXobCTnNbMk2POxOvzOwwP9XqW9fuWVf4nxxno+7sSJE69mR7B7
; OlZliHIJIlo/H0GnyeBRl44VCfa0rarJ4pDfWdJK06rINtvwu1fSCql0ZNXu6+lYWfI7RpTr9jRv4V
; MTb6Y6P+w8laZnTfiEfu+n35sm2EMbEJMvaZXRsZJ5Dm/a0j63yaHApt5MYjyVpmNNclQk2NOwptWy
; x1kJUcak3dc2Jcl9NXmCXYLHRrq0LzT4YiNkTIUyN6J83J/NU2nzNkxbdtXGxor2/d40H1l3Cfvbv7
; r349jgYZIEu806MNeBmlsR16G3BbYVOPSbqc0PMk+lzVsKfmdjRb/9XtdrKFpYJdkI7r+tZiOaKNfd
; U/LnosGXKrYFjmopLnwiwV6/tZltesbGin77vQ2CXVMJrehpiY6Vt/CpzLZA+9ifPnt/K0OBKZ78eC
; qt/9qmWDZiKZN+r/p7xwh2uQd7elq1lrR0yUqvmQ3Nc0hwmZiYWGub66jbYVUZCfZ6rif93i9LLeuI
; +b1uPa3YegyPYN+zZ8+WyrORoonyWB/yuXPnFhFE9HPa0rHK5ZTHU2l11zCnmzL93s9rWOchBwQ71H
; 1jooxyz15YWHhnZmZmR2XZiNeeW2YoUF6QHgrE/2PWUd5IsNPvOb3uFCznDrc29LRCh/5KCPZQ1lG0
; LdAS5W1sC8wx6wgZ2z7753cS7KP5PffDVt2lTNHTig0eyqF/5HZfjygPLTQpQ5TnoJ6bupFg77ffeX
; ig36syBBG0+wo37TU+aT2toRZWSdZx/PjxXRu1sPmiXR3SEpbCUCCsy6d1nkrD16Ur2WbM7yxlftq6
; VGVow++oCBUNH1qCvbDdVw8Fwiz57Rm2BSJS6Rfw2399dytEeR8+ZDyV+n7P6XXT77wWZa1uPS1kI2
; UI9mPHjp0tLGlJyUoPBRbtK9d6K02r5/btzSTGU2l//d7nxopc2rKrthQI9lJ6WqFtgXa6PFSyapLv
; 6HoKO8w16OOHqc+lvL7fRPsePJsg2D1Ou1BPK9TaZbuwOBSY1huL5bv+Gct3/fZ7nXpaoeFvb/gQg4
; efEOyxJ8NEMLGtbYF9TWGHuS5dDCLMNuN+7+rhgX5vx++PX//xR0X8t8QFDB8KwT4oerI2aK00edH6
; nsIOc43Y0ki/83ei38cxT08rVp1CSWsQGwrU2UiXFz7lbl05lTLb7K/fmXUMf72aUvf1gofEBZcDsR
; GIE+V5WM5Bl9nm6NYFOQ9+1kf3e10E+2Nv/mTNW5crwQVfP9WFRaI8f8uRYKffq7uGORHs9Hv61xAE
; e2zwcIAHZQakreDBFLZ6y+FUymyzWsulsYJt2fX4vU49LRsfPhVAdPnqO1vuX/+tDz7f2C/PU0j91z
; blZVr0e7+uLf2e57WVmRFLbwy8Ft6vvfLlRoIICdP6LbVTKYnyZq9zKqVMZpvN+b3qEvZ/OfL52//x
; yc/d9kpZg9AoO4LIPcfvquWNxxS2eUvh5JdjnZ5+78Zr6JtVdUhD8Phff/bF26HNs4NQz++mRvzC9O
; X/fOhzt6vMRvhmas/aPJXS7+36vY3GCmab7do4BzbJOhA8vHZebJ0Fdz6wKYnt+X16+snNktZ/Xfh8
; Jb8M30ztW5Mfavo9Pb83EUTYlp2GjVLClqyjzID5QLZRiUR7SAvr+689cGvUbISnzzTfWHWXk+j39K
; yJMiL9nq7fYz757//8+dtf2P2527/3xNfXY0rsOpBsBhCkIrIPRFp6vY2ED/3sL24Nk40whU3b6iLY
; mXXk4feqswP6PV+/S8nqjx6+fz1UlfK20Q6mpqaeR9D45S9/eRIm4okhjSydjZR5MzGFTd+qPDHy9E
; m/t/X70EbzlVey0ptnYxtqB5DmPXz48O5Lly69vbS09O7p06cvePtAdCaCctffvvg3a1942S9p8c2U
; n1VxKmW2maffxznoscqQr9//8crOD7ccfnjV4zv0gHloe+FmBgJJ3gMHDmybnZ19auPJB4Vd93p+bS
; oj7b5S0mIKm7+NEvyZbeZvowQBtmXna8g6Jud2B5cHyqIpy33YRqsBFoMgiCATgZ08eXJ6bm7uLZSx
; hFSXnl9vEhF/R0nru4vfuvXSvzFwdMGGOZUy2+yODRMQ6Pc8TYjy7+16IKiw65WsJKjI4ilZg765VA
; orCmVBCLIR2PT09B48AWUtIddD26rwzY6+e+Ti6xcmL4/b7ktLx2KnUmab3bSixgr6PV9D1vHVHV9e
; f2ryyc/sepJGKrs80M4G4jmoUuH/INH4ZLUtlqVLEJFsZGZmZscHH3xwHEFER6nQzAhexKNzD31U9f
; AhrT3zTqU8ffbH79rH9Hu+JkS5t9tDOnE9yXZ7n8dzEQ+QYCDRGFjokpZkI4g0iDp6TsR7IXr4MESw
; 0/IzOZU+u/LETRKm/fP7CyvbbzDryNO8iXKpGhUZmqWkrCX3fnxF567EiIEHKWlJJoIgcuLEiVcRpY
; Qb8YYOrVUxwU5Lw3DjeGtl5uK+lVcu8ybSP78zeORnCB7eUKDmNEL3bilpSdCA7d69e0piwic70UNA
; SUtnI/Pz89tR0pqdnV1CNnLkyJF/Dv1wSX+EYGdJK2/TpYuurFGlFZvONnNcVNZXA1EuWYcECuE1vE
; 7aUPCQstadrwclaIgh0RgUwWYjsDNnzhwWXsRmIh7Rjgn2b+y/52NmI3lZjDBlKav7frfBIpeFVX02
; ZB2/9ZMvuI1OUpLyOmnxuFUkkawDFSiddZQKHDYb0ZEH2cjp06f/aSMjmdcEjPfi9FAKs5F8rAxhyj
; mAfvudh4e0DO253lCgDH9LAAmVtHCPlg4r3NdBlEvyMHLw0JCSFuzkyZM/wzeWklZo+FAPoYyip0Vr
; 1oZdL8xTaTds2PZcljLTMWQdmCiHjpUXGGzJSh/0JfvQXVZ79+49NTk5+amsA/d+JBKDceGVtDB8qA
; l2vJANpv5GbCiljJ4WrVkb52TJUyn9nsrv0ydD8NBDgbb9NjS7h6CBjMS28+qsA5WmsbMOD4hEW7du
; fVCXtKCnhZKWDB8iK8ELDOmo4HHoaf3ffXets6TVvlVxI+CpNC+rSseKBHvzpttzbTcVDu8IBjERRF
; 2ykoYoBA+ddeDPlQcPDTvBjh+48cL/AQEkVNKyqdXB4zOXWdJqz+pYL8xTaT5+r/Kmz8aKZsxTz7Xb
; AkMBxA4Fws6ePTulq0q1ZB0h2HZfBBJkIxg+lLKWJdi91jES7M1bnTd6nkr76Xc2VtRnomMVIspFgt
; 3qW3n3XTvbMXR7btXwhg8PHTr0og4i+LMdmZcMhQR7c9aknhEJ9v75nY0V1ZvoWJUlyu1ch9x35V4M
; usEGjsqI8lGh231FBgXDh3brobSKkWBv3tooL7GkRb839TO7aFKyCkmrx0Ru9X1XAkgyWYcHr6SFry
; hpXb16dV62Hm7OhUQIdmQjJNirs7YX/5Bgb8/vbepY0e+jm6djJaMR0kEVI8rxPBzWJYDcyT5Gmyhv
; GrqkJRnJBx98sB8Eu273jUVPXACWtMa3OgjTcV8LT6X9utYk2IczjyjXWYcEkNDgti5hYcvsxn33gN
; WxSjJwaNhsZIPtf17racUIduppVWMp3rBJsNdvKd6wtd9TeU2pGYjyr+y8a/2nr29dLeI6irYF6tmO
; 7IKHRkhPS4/Ny9dQSkaCfThrkigf1XgqrdfvKQZnEuxhE6L8U92p5mAdyjhk9kMHDk89N6vAoeHpaR
; 0/fnyXLCjB4irwIiE9LblQ248+fRPrc5mNhC2nMhHbPvvtdx4efm1FC5+KhgLxHBzI5VBeuY5VKtB6
; Wggi+AUXNmCHD70gguCCC8XhQ9/aJsqreN08lQ5vOWSbMb/3uZQZWvgk8xzSghtT0dWB5tSpU4u7du
; 16xnZZtdqeWzX0BLt0aqGkZfW0RDkytP0QQYTtvr+2LpzkeSrt5zXrq9+LiHJv4ZM366FKVwclcDQ+
; Ud40vIVVeoJdshFb27MkEriRvhPsXfoA8lQ63HXqkt/70lghWYe3LTBElHtaV0lOlDcNq6cF27gg+x
; BA0H6mF5zEFlb1saSVa+limN+N2Uj42nTxZtv1xgqddXjbAot2KtlhbJ119CpwaOhsRIIIspFjx47N
; yvBhEcGOx0Gw9yUb6cMNlm2f/fR7FxsrQjpWuG/FZuIsUY7ggfshOOPeZh0h6JLWnWVVT+nhwyJ1Xz
; yn69lIl7MOz0iw99vvXciy7l380jrWzN7zJ3ffDpWsQtsCZaha2+Li4jFshE1KxyoVWD0tcCOip6XS
; tk8I9tAwTRf1tPpc1uHvzt89p9cthpIVhgJDh15vCDCkWq65jr179z7OrCMAr6R1p933HR1EpGsrJI
; eCbOQLL3ejpMWhu/4R7G3rWNHvo5sQ5XpboO0qLbMtUFdeOjvbUResnhaykRMnTryKiwqCPabqKzYx
; MbH2+oXJy7mWtLpMmI57TcgD9MtyOURpotx2UOHQi+AQ4zrkebItEFkHA8eI8Np9p6amnkcdMKSnZZ
; 2B5zw699BHuRHs7EQKW5fbPun34muTYmANEeW6FBXrJtX3K2X7slDPTR3ewioZPtSpXmipCiwXgr1v
; hOk41qXSXuo6VqlYio0VyDqKiPLQtkCP6xDZdZ114CA9IEaHJtj18KEsrJKvOjPx1H5TVvfl6XP0a8
; Yp/H76ve1rhuABriM0vxFTyw1saeVsR53QelpCsB87duwsAgdEGfUClRjBjmwklSDStcnitq5fbiUt
; Zpv5+l3rWNlu0CKiHDyIs+zpQ0/HisGjBoT0tBBAMGgjw4dFwznf2H/Px22XtEiUV38tqUhLv9dpIR
; 0rWfbkzXTYLEQHEOmwYuBoEB7BvhE49i0sLOzXqWGMYEeX1n3Pfn29rZIWbyLVW+rZCLPN+q5r3Qex
; 0JpZm3UUEeXCdaDLSrYFMni0BJ2NnDx58mdaT0vXF2PpZdMEO0sX9VuKN2lmm835verrK0OBoQOpfR
; x/jymK602BnVfPTR0hPS2o+wqpLiR7KL1simBn1tGcpUSw0+/5Xmu05+qhQDmAekoY9p5i11TAOrUt
; sEvQJS0JJKdOnXoTThReJDZ8iDfEc4e23/zRzx9cqzob4WRxO9Z22yezzXb9Pk62JyUrtOdaXSrp+I
; zdS2QJnijo7t279xSIct2iSx2rxGAl4sGNbDju70J6Wtbh8uaoUk+Lp8/2rQ0f0O/5+j1ElMs9oswQ
; s+Y7Nu5Db5IozwReSQsT7FZPS8TLvBolHqtCT4uEaTrWFMFOojw9v5flnsoQ5eNsC2TwyAgxPS3Ni9
; hhHjv8MwrBzsnidK3OzIA6VulaUVBH8MCmwFAHlc427LZAb4jZmyhn4MgMXrvv5OTkNgwfoo0O3IjU
; KNHD7U2U4rFhCHaWLtK3Oto+6ff0zQvwVsdKB4uyRLndnsqFTx2Dp6e14eiXZPiwiGCHgWCPZSMkTP
; OzKgh2+j0v0yXG0MKnMtsCtQCibAtE56flOkiUdwRWTwuLWTB8iK2H0m7nEez6VLJ5MnEIdp4+87Vx
; yk70e772+JWHVyfndn8YW/gU2lXucR2nT5/eg4Mps46Ow+ppwVDS0kHEEuz6TaYXVv2/D0iYdsGGJd
; iZdeRr4Dq+svOudQSPkDqu/bzrxyyJjnuG6FiR7+gJbLsv7OgGhFTXBHsohQVngoVVW68+zMnijliZ
; jIJZR74m6rm2i6rMwic9CiAHTc11cKK8Z7AEu0ywY/hweXn5jLxZihZWvf2L2YvfXfzWrS6sz6XFCX
; Zmm3kaiHK7ZlZnEJoAD5Ww75SpLoiCLrcFEpvwhg/ffffdQ3b4UGqi3umliGCn5Wc6WFDHKl+ThU92
; GFAHENN+686IyfNEx4pcB/EJNMHuDR/KG8x7o33qTZfwwira8IbA8dbKzMV9K69cZtaRn8Wk12OfYy
; lp2UDD2Q4iCl3SkrkR0dMKnVS8CXZmI/mbZB0IHs+uPHGTQ6H5mEyUQ0E3VH6WDiuvpCX7OuQx6Fjh
; QGkzD7bnEp+BV9ISiXi0/MaCh6fum9MHj/Zr84hykud5mM46vG2BtilGZyN2KJBcBzESPD2tmZmZHY
; uLi8esnlZIIh5v3qenn1xlSSsfK9KxynV9bh8spmOF7qrYOgd8ViV46HZ+bgskxoKdYMfSKuhp2ZJW
; 6FSDr9/Zcv86S1rp2zBEObORtCzEdeghYP01loEIUc6sg6gENhtBSQvZCIYPNcFuh5F07XVYPS1asz
; ZKQGhijSotbqJj5W0LDOlY6eny2LZAPVXO4EGMDQQRraUFO3PmzGEZOJQUODSMJBPsyEa+9h5vOCnY
; uBPlbS+s6rMh6/jqji+vPzX55KrlImO7ySWI2HKVLHzSDTTUsSIqhdXTwpsMw4cg1yHMqIcPQxOtCD
; AYPiTB3q5VWYZiSatZ84hyW4YKff6sCCKeL0Q5J8qJ2uFNsM/Ozj4lelq6f1yn1HYoCcOH4y6sog1v
; da0XJsFev8WIcjOv8ZnPnx4i1HNdJMqJVqDbfZGJiJ4WshCdGocm2OVxEuzNWROZArOReqwMUW53l4
; c+f9KeSwFEolV42cjJkyenZfhQNpXZbWVW7ZMEe/3W5I2dBHt1JkQ5tgXa0rBVyg2VtELbApl1EEkg
; NHyIN+3Vq1fnZThpamrqRqg2ywn2eqzN9cIUXxzPRMdKFj7pDkev29FyjfK5s1yHzjpwABwQRNsI6W
; khgMC02mfsTf/o3EMfMRupxlIoJ3FP+mgWKlnJtsBYo4omypF9YFsgDnTMOojkYfW0rly5Mrm4uDht
; tbQ8jR4JLpKNMIiMZqktfGK7b3mThU8xEcTQtkBbvsLnDe25x48f32W3BbI9l0gWXkkL3R5Sjy3Tsy
; 4EO9t9h7OUSWwS7HHTC5+8z4N9TA8LhoYC9WGOWQeRDewEO97AmGCHRLyUsySgxDR67nv26+ssaRVb
; kY5Vaq+TBPtvTNpzQZRbnbmJiYm12FAgTEpVOsvX2wJZsiKyhdXTEoJdth6G9LT0yevou0cu/ujnD6
; 6RYPctx4VPJNh/bZbrsPNS+IwgiMS4DphsC9QdVsw6iE4gsD73mZCeVujDxHbfz1rOZSHd7pvT667K
; 0J4b4zo0Z2izdG4LJHoHCSK6U0vraekPCxdWxS01onxU6yPBLkS5tOeGiHLvc+BxHRul4Xl0POrAQR
; 0ropPQBLvW09IT7EjFLdluP2R9XljVRTK6LwS7lKzKEuXewid92CLXQfQOXkkLrYaipwVhRhmAihHs
; yEb6pKeVC1E+7u/XRYLd07HCe1u6qGI8oMx+yGdCyr5aBJHBg+gdPD2tQ4cOvYjBQww/yUkr9sHCdH
; sfSlp9GsjrWjYS07HaVKcGvxcYrrUZCD4XWOrGrIMgBn42sry8PCV6WkUE+2Y5q+N6Wn2cn+iCnhZ0
; rO6e8YcCtY5VbPmTwwW+JG3xDB4EcQchPa3Q8KEnidI1gr0rRPk4lmvJThY+TR3aGz38eGoMMvuhDR
; Pl1LEiiAg8PS0MH4qir5CIRQtzkI3cc/yurKVQOLX92WuRS/kOwcMOBerDT2woEAHEI8rJdRBESdiS
; FrIRlLT01sOYEik+hBg+zJFgZ9bhWw4EuyXKrTaVHH689633XAQRrJll8CCIIaEn2CWIgGD3Slqxmn
; FOJS1mHfleoxhRHprnCA0FcmcHQVQAq6clJS3R09IEu1c3zolgp7RHeUuJYAdRHlozaxs97PtTt/B6
; 2wIZPAiiAoT0tKQffmlp6V1bN7Z15lQJ9hx1rFKxtoOuLHzymjpCjR6SjQifd0e/ikOBBFEnNMFuhw
; /BjcjwYVFPfUoEO0tW1V3Dpgl2q2MlGYYeDgwR5XZbIIcCCaIhaD0tGT68cuXKEQwfIhMJZSD6BPjc
; oe0328xGSJRXa03qaQlR7ulY4b0lWXBo8FUyEFHavXTp0tuTk5PbqGNFEA3B6mmdPXv2+cXFxTmtp+
; UpmOqTYVt6Wsw68r229y5+aR3tuaHsVr+3YsrSmuvAIYhDgQTRMDTBLtmI1tPSO9hDS3ma1NPquo5V
; KlZHu69kHT99fetqqINqnG2BDB4E0RI8PS0Q7CI6h0U7saU8sO9suX8dJa2vvVdP+YNEefNWVTYi7b
; m2FVcOJh5RroOLtJ3rTYEMHASREDw9rfPnz09u1Jc3yXWdjXgfdnzQ8QF/dO6hj6pu92XJqj0bp90X
; 7bmWKLfChrDYJk3NdUAEkUQ5QSQM3e6LbGTjg/vCBrF+ILZfxA5xPT395GoVBDuJ8nRsWIJd2nNDRP
; kbzrZAOZh4XAfKqrY9l0Q5QSQI3e4rQQTZiG6ZxAcbMvBvBLYejkuwM+tIz8r6RHSsyhDl9r3jDbNi
; opzquQSREWxJC0EEtry8PCcDhzagVEGwS8mEwSNNixHsWsfKznHEiHIJFMhw8X4C52YHAxk8CCJDhE
; paCwsL52VpFT70GOwKEey4aZQpaTHryMesrzwdKz0QGBsKxL9J8IBhFolcB0F0BFZPC0HkyJEjf3/9
; +vXDZQh2WSf6l2/+YC1EsLM9Nz9DBvLSv+78cMvhh1e9kpV0UMVUn3UZC5kHDiRnz55l8CCIrkFnI3
; Nzc89cunRptybYvVKWLV1YPS1NlLM9Ny9D1vH4m4+uYuFTyO+bQpzOtsDApsCDe/fufRyZLhc+EUQH
; YRdWWYLdDh96pQsh2L+7+K1bL/0bs45cg8f3dj1wy1PHDelYxbYFkusgiB4hRrBvfD0jwSQ2M4KFVa
; 9fmLzclfW5fQkcIMq94CGNFSG/4zFwZTKcivcA1sx6C5/YnksQHYedYBeCXUQZPT0tW7rAzeZHP39w
; rWk9LdpowQNEuVd+gq/1KoDYrJB0XB09epRcB0H0GR7BjpKWbvfVpQ1vbgSG4cPUF1b1OXDYhU92fW
; zIQgufwHdwbwdBEJsommDHTUNPHoeCSE7rc/sSPGJDgTF/SkkrxHVIAGHgIAiiMBvRA2Le9LqcbHNY
; n9t10zpWVlrddlV5q2ZD2wIpgkgQRBSaYNfZCHr8tZ6WVyvXE+zf2H/Px8xGmjdPx0qCBEhwz2cyOI
; gsUwKH7JbxiHLqWBEEEYSnp7WRiUxZ+RO7sMp2arWxsKrvwcNOlGufIIDEfCaZh5QssRaARDlBEEPD
; lrQuXLjwjx7BrieVvfJIUwur+h44/vi1P7j153//g1shrsOKIMa2BWoRRAYPgiBGhhDsuJmECPai8k
; hZPS3aaMFDz3XYtmsv45BALz6zRLkuYTJwEAQxFpCNbN269cEQwY65EWQkse10eHzbwa2r9xy/a53Z
; yPimiXLbkislqCIRRPhMfKeDhxiCCIMHQRCVwGv3PXLkyE6IMob0tGyZBBPszEbGM48o12UoIcBjft
; DP3fDbP1iugzpWBEFUjiI9LU2wh7bUbdbg2e47cvAIEeXewGeRH0CUcyiQIIhGUbSwSuYJ7ACi3NCE
; YEc2wiBSLnB8Zedd6yHpdY8otyUtGzzQnsttgQRBtIKQnpYQ7LKwSgIKCfbRgweyjpC0undd5bl6KN
; DjOjhRThBEa4hNsN+4cWMO/IiUtmIEO0tafuCwOlYSNGSnfZltgQjkMAQQbgskCCI5eAT7tWvXZoYh
; 2P/2xb9ZYzbym+ABojw2FFh0PbU0yQb2c66DIIhkYQl2bD0MqftaYlfX7/uejdw9c9f6T1/f+pmWaK
; +EJcR50VAgtgWS6yAIInnECHbR04rNKmiCvU/ZiJSsnpp8ctVO+dtA60nH2MFA0bHS6rnUsSIIInl4
; BLu0+6KsJTX5kDaT3Bi3H336Jtbn5hQIRg0eQpTbDAJ8RxHXgQCitwWS6yAIImuECParV6/+PKSnZc
; s1uBk+d2j7za7qaYWIcpnnwDWKTfl7g4EbX19i8CAIohMos7AqNscgvEnXSlpF6rmx3Svev+uFTwwc
; BEF0BmXX56JcY4feurawSnSsvKFAT9HYTpd714glK4IgOo9YNoL6vR5688o2uRPsWsfKbgssIsr1UK
; BsCwRR7ulYkSgnCKKTCOlpLSwsnMfwYVmC/S/f/MFaTgurvJKVZBi2PTdElEvwwDVi1kEQRC+hS1rS
; 7js3N/fM9evXD6NLK0aw62G6HBZWhYhynXVIEPF+V1vCAm+EwUAGD4Igeg1d0pqdnX2qLMFu9aBSLW
; kheGAoMFSW0o9LC28RUS6t0QwcBEH0HsMS7KHhw5QIdhDlyDrstkC8zhjXIRmHaF2RKCcIgiiBEMGO
; er9oahUJCGJm5PULk5fbzEa0jpWnSxUTlpTn43n4vTkUSBAEURIewb5///5dly9fng3paXk3XyHYm8
; 5GQkS5DiDDiCBOT0/vYfAgCIIYAmX0tORG7M1KwJps9y1LlIeWa9l/Q3vuRhnreRs82J5LEARRAkUL
; q1DewSldBxS5Meubt3AjdQYPcB2hbjFL+NssQ3ecaa6DE+UEQRBjoIhgl4VVElBi6r5Vl7R01mEnyG
; NEubctkEQ5QRBETQgR7Bg8vHr16rwQzjGCHUHkG/vv+biKklZIx0rmU0IzHZar4VAgQRBEA/CykWvX
; ru0fhmAfd2GV6Fh5wUMyi4mJibXQZLktYSHocSiQIAiiIWiC/ezZs89bbiSkXCtBZVQ9LWQdX93x5f
; UdL26PBij9mCbKbeDQC5+oY0UQBNEQdLuvXVgF0wR7qKw1DMEuRHlIWj30MxA4PKKc7bkEQRAtwitp
; SbsvyHWtqRXiI/A4hg//9K0/uOWVtDyiXGcRsQAlU+XyvI0s6V29t4PBgyAIomV4BPvp06f3hPS0PD
; 4Cz7ElrRBRLkFE7+QIlbS0nTlz5rAEDAkgDBwEQRAto6yeltWjsiUpKWnFiHJvKNDjXHSAYdZBEASR
; OMqsz8VXy0no7AQEO4jyUAeVJuN1IBHORQJHSMcKgW5AEARBpIfQwioEESytwtyFBBTMbMRmNSRYxB
; Y+2W2BqhPsIIlygiCIDOHpaZ04cWJGhg/LEOzIImIDipKFSGaDAAKy3LbnUseKIAgiM1g9LWw9vHbt
; 2ozIw4cIdt2ea3eXx4jyje+37+TJkz9j1kEQBNEBaIJdth6WIdjttkBP64oiiARBED1AGYIdwQTbAE
; NlLSlV2Q4rch0EQRAdR6zdF7yIDPsVLaySaXcGD4IgiJ7BI9jff//9N0MLq2y5amZmZn5ycnKbbc8l
; UU4QBNEDeAurrJ6WHQhkyYogCILYRJkJdp2RMHgQBEEQn0IRwc7AQRAEQQQRyka0CCKDB0EMBv8OZU
; 71qhH8NXsAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.60mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.55mm


M140 S110 ; set bed temperature
M104 S245 T0 ; set temperature
;TYPE:Custom
print_start EXT_TEMP=245 BED_TEMP=110
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
T0
G92 E0
; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)
; at 240C: 0.06
; at 255C: 0.064
; at 270C: 0.044

;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06
;SET_PRESSURE_ADVANCE ADVANCE=0.06
; Still seems too much.  Testing a bit less.
SET_PRESSURE_ADVANCE ADVANCE=0.04
M109 S245 T0 ; set temperature and wait for it to be reached
M190 S110 ; set bed temperature and wait for it to be reached
;LAYER_CHANGE
;Z:0.24
;HEIGHT:0.24
G1 Z0.24 F12000
G1 E-1.25 F1800
M204 P2000
G1 Z0.38 F12000
G1 X82.5 Y162.175
G1 Z0.24
G1 E0 F1800
;TYPE:External perimeter
;WIDTH:0.55
G1 F2400
G1 X5.325 Y162.175 E3.5316
G1 X5.325 Y7.825 E10.59479
G1 X159.675 Y7.825 E17.65798
G1 X159.675 Y162.175 E24.72117
G1 X82.56 Y162.175 E28.25002
;WIPE_START
M204 P4000
G1 X82.3 Y161.829 F12000
;WIPE_END
;LAYER_CHANGE
;Z:0.44
;HEIGHT:0.2
G1 Z0.44 F12000
M104 S235 T0 ; set temperature
M140 S115 ; set bed temperature
G92 E0
G1 E-10 F1800
G1 Z0.58 F12000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)
; at 240C: 0.06
; at 255C: 0.064
; at 270C: 0.044

;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06
;SET_PRESSURE_ADVANCE ADVANCE=0.06
; Still seems too much.  Testing a bit less.
SET_PRESSURE_ADVANCE ADVANCE=0.04
M204 P2000
G1 X82.5 Y162.375
G1 Z0.44
;WIDTH:0.45
G1 F7200
G1 X5.125 Y162.375 E2.40953
G1 X5.125 Y7.625 E7.22858
G1 X159.875 Y7.625 E12.04764
G1 X159.875 Y162.375 E16.86669
G1 X82.56 Y162.375 E19.27435
;WIPE_START
M204 P4000
G1 X82.3 Y162.029 F12000
;WIPE_END
;LAYER_CHANGE
;Z:0.64
;HEIGHT:0.2
G1 Z0.64 F12000
G92 E0
G1 E-10 F1800
G1 Z0.78 F12000
; Filament-specific end gcode 
;END gcode for filament
T0
G92 E0
; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)
; at 240C: 0.06
; at 255C: 0.064
; at 270C: 0.044

;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06
;SET_PRESSURE_ADVANCE ADVANCE=0.06
; Still seems too much.  Testing a bit less.
SET_PRESSURE_ADVANCE ADVANCE=0.04
M204 P2000
G1 X82.5 Y162.375
G1 Z0.64
G1 E10 F1800
G1 F7200
G1 X5.125 Y162.375 E12.40953
G1 X5.125 Y7.625 E17.22858
G1 X159.875 Y7.625 E22.04764
G1 X159.875 Y162.375 E26.86669
G1 X82.56 Y162.375 E29.27435
;WIPE_START
M204 P4000
G1 X82.3 Y162.029 F12000
;WIPE_END
M106 S127.5
;LAYER_CHANGE
;Z:0.84
;HEIGHT:0.2
G1 Z0.84 F12000
G92 E0
G1 E-10 F1800
G1 Z0.98 F12000
; Filament-specific end gcode 
;END gcode for filament
T1
G92 E0
; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)
; at 240C: 0.06
; at 255C: 0.064
; at 270C: 0.044

;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06
;SET_PRESSURE_ADVANCE ADVANCE=0.06
; Still seems too much.  Testing a bit less.
SET_PRESSURE_ADVANCE ADVANCE=0.04
M204 P2000
G1 X82.5 Y162.375
G1 Z0.84
G1 E10 F1800
G1 F7200
M106 S204
G1 X5.125 Y162.375 E12.40953
G1 X5.125 Y7.625 E17.22858
G1 X159.875 Y7.625 E22.04764
G1 X159.875 Y162.375 E26.86669
G1 X82.56 Y162.375 E29.27435
M106 S127.5
;WIPE_START
M204 P4000
G1 X82.3 Y162.029 F12000
;WIPE_END
G92 E0
G1 E-1.25 F1800
G1 Z0.98 F12000
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
; Filament-specific end gcode 
;END gcode for filament
print_end    ;end script from macro
; filament used [mm] = 47.52, 38.55
; filament used [cm3] = 0.11, 0.09
; filament used [g] = 0.14, 0.12
; filament cost = 0.00, 0.00
; total filament used [g] = 0.26
; total filament cost = 0.01
; total layers count = 4
; estimated printing time (normal mode) = 35s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,165x0,165x170,0x170
; bed_temperature = 115,115
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonicgapfill
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0
; bridge_acceleration = 1500
; bridge_angle = 0
; bridge_fan_speed = 70,70
; bridge_flow_ratio = 100%
; bridge_internal_fan_speed = -1,-1
; bridge_overlap = 100%
; bridge_overlap_min = 80%
; bridge_speed = 40
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0,0
; clip_multipart_objects = 0
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 4000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 3,3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = print_end    ;end script from macro
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 0
; external_perimeter_fan_speed = 80,80
; external_perimeter_overlap = 100%
; external_perimeter_speed = 120
; external_perimeters_first = 1
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #21FF06;#0000FF
; extruder_fan_offset = 0%,0%
; extruder_offset = 0x0,0x0
; extruder_temperature_offset = 0,0
; extrusion_axis = E
; extrusion_multiplier = 0.92,0.92
; extrusion_spacing = 
; extrusion_width = 0.45
; fan_always_on = 1,1
; fan_below_layer_time = 0,0
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #FF0000;#FF0000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cooling_zone_pause = 0,0
; filament_cost = 25,25
; filament_custom_variables = ;
; filament_density = 1.25,1.25
; filament_diameter = 1.75,1.75
; filament_dip_extraction_speed = 70,70
; filament_dip_insertion_speed = 33,33
; filament_enable_toolchange_part_fan = 0,0
; filament_enable_toolchange_temp = 0,0
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_overlap = 100%,100%
; filament_max_speed = 0,0
; filament_max_volumetric_speed = 0,0
; filament_max_wipe_tower_speed = 0,0
; filament_melt_zone_pause = 0,0
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Tuned 2020-12-27 to PA=0.08 on both 0.3 and 0.2 layers.";"Tuned 2020-12-27 to PA=0.08 on both 0.3 and 0.2 layers."
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = f0-abs-kvp;f0-abs-kvp
; filament_shrink = 100%,100%
; filament_skinnydip_distance = 31,31
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_toolchange_part_fan_speed = 50,50
; filament_toolchange_temp = 200,200
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_use_fast_skinnydip = 0,0
; filament_use_skinnydip = 0,0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5,0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 40%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 94%
; first_layer_acceleration = 2000
; first_layer_bed_temperature = 110,110
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0.55
; first_layer_flow_ratio = 100%
; first_layer_height = 0.24
; first_layer_infill_speed = 60
; first_layer_min_speed = 0
; first_layer_size_compensation = -0.15
; first_layer_size_compensation_layers = 1
; first_layer_speed = 40
; first_layer_temperature = 245,245
; full_fan_speed_layer = 0,0
; gap_fill = 1
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 80
; gcode_comments = 0
; gcode_filename_illegal_char = 
; gcode_flavor = sprinter
; gcode_label_objects = 0
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 4000
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autosmall
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.6
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 20%
; infill_speed = 150
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.2
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = ignore
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 0,0
; max_gcode_per_second = 1500
; max_layer_height = 0,0
; max_print_height = 120
; max_print_speed = 250
; max_speed_reduction = 90%,90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 50,50
; min_layer_height = 0.07,0.07
; min_length = 0.035
; min_print_speed = 10,10
; min_skirt_length = 5
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = bridges
; notes = 
; nozzle_diameter = 0.4,0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 50%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 2000
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 150
; perimeters = 4
; physical_printer_settings_id = f0
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = v0-abs
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = dz
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; remaining_times_type = m73
; resolution = 0
; resolution_internal = 0.2
; retract_before_travel = 2,2
; retract_before_wipe = 0%,0%
; retract_layer_change = 0,0
; retract_length = 1.25,1.25
; retract_length_toolchange = 10,10
; retract_lift = 0.14,0.14
; retract_lift_above = 0,0
; retract_lift_below = 0,0
; retract_lift_first_layer = 0,0
; retract_lift_top = "All surfaces";"All surfaces"
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 30,30
; seam_angle_cost = 100%
; seam_gap = 15%,15%
; seam_position = rear
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 1
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 0
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 4,4
; small_perimeter_max_length = 10
; small_perimeter_min_length = 6
; small_perimeter_speed = 40
; solid_fill_pattern = monotonic
; solid_infill_below_area = 6
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 150
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)\n; at 240C: 0.06\n; at 255C: 0.064\n; at 270C: 0.044\n\n;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06\n;SET_PRESSURE_ADVANCE ADVANCE=0.06\n; Still seems too much.  Testing a bit less.\nSET_PRESSURE_ADVANCE ADVANCE=0.04";"; 2021-09-23: 255C, 0.92 ext, Galaxy Black on Dragon HF w/0.4 nozzle and 0.45 width and 0.3mm layers; cube with 0.002 factor yielded 0.064 best setting (.06 --> .07 OK range)\n; at 240C: 0.06\n; at 255C: 0.064\n; at 270C: 0.044\n\n;2022-03-20  After nozzle change: 0.4 E3D nozzle @ 235C, 80 mm/s: 0.054 --> 0.06\n;SET_PRESSURE_ADVANCE ADVANCE=0.06\n; Still seems too much.  Testing a bit less.\nSET_PRESSURE_ADVANCE ADVANCE=0.04"
; start_gcode = print_start EXT_TEMP=[first_layer_temperature] BED_TEMP=[first_layer_bed_temperature]
; start_gcode_manual = 0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = honeycomb
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 40
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 235,235
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 0
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 12
; thumbnails = 32x32,400x300
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = ;
; toolchange_gcode = 
; top_fan_speed = -1,-1
; top_fill_pattern = monotonicgapfill
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 60
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_acceleration = 1500
; travel_speed = 200
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1,1
; wipe_speed = 0,0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0.1
; z_offset = 0
; z_step = 0.005
